---
title: "arima_forecasting"
author: "Mihkmihk"
date: "2024-01-30"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(forecast)
library(timeSeries)
library(tseries)
library(fpp2)
library(lubridate)
library(stats)
library(dplyr)

disease_forecast_csv <- 
  read_csv("Mean Monthly Disease Percent Incidence.csv")


pest_forecast_data <- 
  read_csv("pests_forecast_dataset.csv")

# FAW
faw_ts_data <- ts(pest_forecast_data$`Fall Armyworm`, 
                  start = c(2020, 5), 
                  end = c(2023, 7),
                  frequency = 12)

# Leaf Blight
blight_ts_data <- ts(disease_forecast_csv$leafblight, 
                  start = c(2020, 5), 
                  end = c(2023, 7),
                  frequency = 12)

```

```{r}
# NO DIFFERENCING on faw because it is STATIONARY
acf(faw_ts_data, main = "ACF of FAW Data\n May 2020 - Aug 2023")
pacf(faw_ts_data, main = "PACF of FAW Data\n May 2020 - Aug 2023")
adf.test(faw_ts_data, alternative = "stationary", k=0)
plot(faw_ts_data)

faw_auto_arima_model <- auto.arima(faw_ts_data)
print(summary(faw_auto_arima_model))
checkresiduals(faw_auto_arima_model)


faw_forecast <- forecast(faw_auto_arima_model, 
                         level = c(95),
                         h = 3 * 12)

autoplot(faw_forecast)
# write.csv(faw_forecast, "FAW_Forecast.csv")
```

```{r}
# The Ljung-Box Q-test is a "portmanteau" test 
# that assesses the null hypothesis that a series of 
# residuals exhibits no autocorrelation for a fixed number of lags L 
fit_faw_arima <- arima(faw_ts_data, order = c(2, 1, 1))
checkresiduals(fit_faw_arima)
```




```{r}
# use 1st DIFFERENCING on Leaf Blight because it is STATIONARY
acf(diff(blight_ts_data), main = "ACF of Differenced Leaf Blight Data May 2020 - Aug 2023")
pacf(diff(blight_ts_data), main = "PACF of Differenced Leaf Blight Data May 2020 - Aug 2023")
adf.test(diff(blight_ts_data), alternative = "stationary", k=0)
plot(diff(blight_ts_data))

blightSpot_auto_arima_model <- auto.arima(blight_ts_data, d = 1)
print(summary(blightSpot_auto_arima_model))
checkresiduals(blightSpot_auto_arima_model)


blightSpot_forecast <- forecast(blightSpot_auto_arima_model, 
                         level = c(95),
                         h = 3 * 12)

autoplot(blightSpot_forecast)

# write.csv(blightSpot_forecast, "Leaf_Blight_ARIMA_Forecast.csv")


Box.test(blightSpot_forecast$residuals, lag = 5, type = "Ljung-Box")
```














