---
title: "corn_variety_edit"
author: "Mihkail Cornell"
date: "2023-09-05"
output: html_document
---

```{r}
library("dplyr")
library("ggpubr")
library("tidymodels")
library("tidyverse")
library("ggpubr")
library("broom")
library("multcompView")
set.seed(123)
insect_raw$Variety %>% unique()
```

```Corn variety engineering```
```{r}
insect_variety_edit <-
  insect_raw %>%
  mutate(variety = case_when(str_detect(Variety, "^[OPV]+([_ ])+([WC]+|[WwHhIiTtEe]+)$") ~ "OPV White",
                             str_detect(Variety, "^[OPV]+([ _]*)+[YyEeLlOoWw]+") ~ "OPV Yellow",
                             str_detect(Variety, "^(M[ACHOacho]+)[_ ]*(F1)+") ~ "Macho F1",
                             str_detect(Variety, "^(S+[WwEeEeTt])(\\s)*([CcOoRrNn]+)") ~ "Sweet Corn Hybrid",
                             str_detect(Variety, "M[aALlAaGgKkIiTt]") ~ "Malagkit",
                             str_detect(Variety, "\\b(Y+[EeLlLlOoWw_* COoRrNn]+)+") ~ "Yellow Corn Hybrid",
                             str_detect(Variety, "(FILIPINA_703)+|(Filipina 703)+") ~ "Filipina 703-HY",
                             str_detect(Variety, "^([Cn])+") ~ "Cn 224-OPV White",
                             str_detect(Variety, "^\\(HYBRID YELLOW CORN\\)|^[Yellow Corn Hybrid]$") ~ "Hybrid Yellow Corn",
                             str_detect(Variety, "^([Mem]+[ei]s+)+") ~ "Memphis Native White Corn",
                             str_detect(Variety, "^((FILIPINA_802)+|(Fi[l+ĺ]+[iu]+(pi)+[n ]+a+(\\s|-))*802)+") ~ "Filipina 802-Hybrid White",
                             str_detect(Variety, "[NK]+[ ]*[6410]+") ~ "NK6410 BT/GT Hybrid",
                             str_detect(Variety, "B[Rr][Ii]+[GgHhTt]") ~ "Bright Jane",
                             str_detect(Variety, "^J") ~ "J505",
                             str_detect(Variety, "^(Native) ([Ww]hite)$") ~ "Native White",
                             str_detect(Variety, "^(P+|[Pioneer]+)") ~ "Pioneer 266",
                             str_detect(Variety, "^(NSIC GM)") ~ "NSIC GM CN38",
                             str_detect(Variety, "^[Super 999]+") ~ "Super 999-HY",
                             str_detect(Variety, "\\b(Supreme 5150)+") ~ "Supreme 5150-HY",
                             str_detect(Variety, "B118G") ~ "B118G-Hybrid Yellow",
                             str_detect(Variety, "T+[INIGinig]+[u]*[IiBb]") ~ "Tiniguib",
                             str_detect(Variety, "G[LUTINOUSlutinous]") ~ "Glutinous White",
                             str_detect(Variety, "Bio [Ss]eed") ~ "Bio Seed",
                             str_detect(Variety, "(BioCorn 108)+") ~ "BioCorn 108-HY",
         TRUE ~ Variety))

number_sampled_plants <- 20
percent_100 <- 100
insect_variety_edit$variety %>% unique()
```

```Rating of 1 is classified as No damage to very slight```
```Corn Borer, Semi-looper, earworm```
```Borer```

```{r}
# Corn borer
borer_df_ev <- 
  insect_raw %>%
  select(FarmID, `Collection Date`, Province, Municipality, `Crop Stage`, Treatment, `Corn Type`, Variety, contains("Corn Borer - Damage Rating ")) %>%
  filter(Municipality != "Santa Rita" & Municipality != "Hilongos")

borer_df_ev$collect_date <- 
  as.Date(borer_df_ev$`Collection Date`, "%B %d, %Y")

borer_dmg_ev <-
  borer_df_ev %>% 
  mutate(Year = year(collect_date), Month = month(collect_date))

borer_joined_ev <-
  borer_dmg_ev %>% 
  left_join(monthly_averages, by=c('Year', 'Month')) %>%
  # mutate_at(c(9:28), as.factor) %>%
  # mutate(across(contains("Corn Borer - Damage Rating "), 
  #        ~ case_when( . < 2 ~ "No",
  #                     . < 4 ~ "Light",
  #                     . < 6 ~ "Moderate",
  #                     . < 8 ~ "Severe",
  #                     . < 10 ~ "High"), 
  #        .names="Class_Infest_{.col}")) %>%
  # mutate(across(contains("Class_Infest_Corn Borer - Damage Rating "), ~classification_dmg(.))) %>%
  # # get the modal observation rating
  #  mutate(Modeborer_class_infest = getmode(c_across(contains("Class_Infest_Corn Borer - Damage Rating ")))) %>%
  # # create ranks column
  # mutate(borer_mode_classification = rank(Modeborer_class_infest)) %>%
  rowwise() %>%
  mutate(sum_no = sum(c_across(starts_with("Corn Borer - Damage Rating ")) == "1"),
         sum_light = sum(c_across(starts_with("Corn Borer - Damage Rating ")) == "3"),
         sum_moderate = sum(c_across(starts_with("Corn Borer - Damage Rating ")) == "5"),
         sum_severe = sum(c_across(starts_with("Corn Borer - Damage Rating ")) == "7"),
         sum_high = sum(c_across(starts_with("Corn Borer - Damage Rating ")) == "9"),
         average_damage_borer = (((3 * sum_light) + (5 * sum_moderate) + (7 * sum_severe) + (9 * sum_high)) / (number_sampled_plants)),
         damage_rating_borer = (((3 * sum_light) + (5 * sum_moderate) + (7 * sum_severe) + (9 * sum_high)) / (number_sampled_plants * 9)) * percent_100,
         incidence_borer = ((sum(c_across(sum_light:sum_high))) * percent_100) / number_sampled_plants,
         )


View(borer_joined_ev)

# borer_joined_ev %>%
#   count(Province, Municipality, `Corn Type`)

summary_borer <-
  borer_joined_ev %>%
  group_by(Province, Municipality, `Corn Type`, Treatment) %>%
  remove_missing(na.rm=TRUE) %>%
  summarise(observations = n(),
            sum_avg_dmg_borer = sum(average_damage_borer),
            sum_dmg_rate_borer = sum(damage_rating_borer),
            sum_incidence_borer = sum(incidence_borer))

View(summary_borer)

summary_borer %>%
  ggplot(aes(sum_incidence_borer)) +
  geom_density()

summary_borer %>%
  ggplot(aes(sum_incidence_borer)) +
  geom_histogram()

summary_borer %>%
  ggplot(aes(sample=sum_incidence_borer)) +
  stat_qq() +
  stat_qq_line()

summary_borer %>%
  ggplot(aes(`Corn Type`, sum_incidence_borer)) +
  geom_boxplot()

summary_borer %>%
  ggplot(aes(Treatment, sum_incidence_borer)) +
  geom_boxplot()


library("nortest")
library("moments")
library("stats")
library("MASS")
library("car")

ggqqplot(summary_borer$sum_incidence_borer)

# Kolmogorov Smirnov test for normality samples > 50
ks_test_borer <- ks.test(summary_borer$sum_incidence_borer, 'pnorm')

# Anderson-Darling Test is a goodness-of-fit test that determines how well your data fits a given distribution. 
# This test is most typically used to see if your data follow a normal distribution or not.
# It is a modification of the Kolmogorov-Smirnov (K-S) test and 
# gives more weight to the tails than does the K-S test.
ad_test_borer <- ad.test(summary_borer$sum_incidence_borer)

skew_borer <- skewness(summary_borer$sum_incidence_borer)
kurt_borer <- kurtosis(summary_borer$sum_incidence_borer)

# Jarque-Bera Normality Test performs a goodness-of-fit test that 
# determines whether or not sample data have skewness and 
# kurtosis that matches a normal distribution.
jarq_borer <- jarque.test(summary_borer$sum_incidence_borer)

# Bartlett’s test is used to test if k samples are from populations with equal variances. 
# Equal variances across populations are called homoscedasticity or homogeneity of variances.
bartlett_fertilizer_borer <- bartlett.test(sum_incidence_borer ~ Treatment, summary_borer)
bartlett_corntype_borer <- bartlett.test(sum_incidence_borer ~ `Corn Type`, summary_borer)
bartlett_municipality_borer <- bartlett.test(sum_incidence_borer ~ Municipality, summary_borer)
bartlett_province_borer <- bartlett.test(sum_incidence_borer ~ Province, summary_borer)
bartlett_fert_corn_borer <- bartlett.test(sum_incidence_borer ~ interaction(Treatment, `Corn Type`), summary_borer)


# Null hypothesis is variances across all samples are equal. 
# Levene’s test is an alternative to Bartlett’s test when the data is not normally distributed.
levenes_fertilizer_borer <- leveneTest(sum_incidence_borer ~ Treatment, summary_borer)
levenes_corntype_borer <- leveneTest(sum_incidence_borer ~ `Corn Type`, summary_borer)
levenes_municipality_borer <- leveneTest(sum_incidence_borer ~ Municipality, summary_borer)
levenes_province_borer <- leveneTest(sum_incidence_borer ~ Province, summary_borer)
levenes_fert_corn_borer <- leveneTest(sum_incidence_borer ~ interaction(Treatment, `Corn Type`), summary_borer)

summary_borer$order_treat <- ordered(summary_borer$Treatment,
                         levels = c("BRFR", "RFR", "ARFR"))

summary_borer$factor_corn <- factor(summary_borer$`Corn Type`)

library(onewaytests) # Brown-Forsythe Test (one-way anova)
bf_fertilizer_borer <- bf.test(sum_incidence_borer ~ Treatment, summary_borer)
bf_corntype_borer <- bf.test(sum_incidence_borer ~ factor_corn, summary_borer)

# AnOVa
aov_fert_borer <- aov(sum_incidence_borer ~ Treatment, summary_borer) %>% summary()
t.test_corn_borer <- t.test(sum_incidence_borer ~ `Corn Type`, summary_borer)

# wilcoxon test - corntype non normal
wilcoxon.test_corntype_borer <- wilcox.test(sum_incidence_borer ~ `Corn Type`, summary_borer)
# perform kruskal-wallis test on corntype 
kruskal_wallis_corntype_borer <- ks.test(sum_incidence_borer ~ `Corn Type`, summary_borer)

# Two way AnOVa
aov_fert_corn_borer <- aov(sum_incidence_borer ~ Treatment + `Corn Type`, summary_borer) %>% summary()
# AnOVa with Interaction
aov_fert_corn_inter_borer <- aov(sum_incidence_borer ~ Treatment*`Corn Type`, summary_borer) %>% summary()


# Create transformed objects using bestNormalize
library("bestNormalize")
bestNorm_borer <- predict(bestNormalize(summary_borer$sum_incidence_borer, out_of_sample = FALSE, loo = TRUE))
borer_joined_ev$trans_incidence_borer <- predict(bestNormalize(borer_joined_ev$incidence_borer, out_of_sample = FALSE, loo = TRUE))


# summary_borer$orq <- transfo(summary_borer$sum_incidence_borer, type = "bestObj", robust=FALSE)$Y[,"X"]
summary_borer$orq <- bestNorm_borer

# Test of Normality after transformation
ks_test_borer_trans <- ks.test(summary_borer$orq, 'pnorm')
ad_test_borer_trans <- ad.test(summary_borer$orq)
skew_borer_trans <- skewness(summary_borer$orq)
kurt_borer_trans <- kurtosis(summary_borer$orq)
jarq_borer_trans <- jarque.test(summary_borer$orq)


# Test of Homoskedasticity after transformation
levenes_fertilizer_borer_trans <- leveneTest(orq ~ Treatment, summary_borer)
levenes_corntype_borer_trans <- leveneTest(orq ~ `Corn Type`, summary_borer)
levenes_municipality_borer_trans <- leveneTest(orq ~ Municipality, summary_borer)
levenes_province_borer_trans <- leveneTest(orq ~ Province, summary_borer)
levenes_fert_corn_borer_trans <- leveneTest(orq ~ interaction(Treatment, `Corn Type`), summary_borer)

summary_borer %>%
  ggplot(aes(orq)) +
  geom_density()


# anova on Transformation
aov_fert_borer_yj <- aov(orq ~ order_treat, summary_borer) %>% summary()
aov_corn_borer_yj <- aov(orq ~ factor_corn, summary_borer) %>% summary()

# Two way AnOVa
twoway_fert_corn_borer_yj <- aov(orq ~ order_treat + factor_corn, summary_borer)
tukey_fert_corn_borer <- TukeyHSD(twoway_fert_corn_borer_yj)

# AnOVa with Interaction
aov_fert_corn_inter_borer_yj <- aov(orq ~ order_treat*factor_corn, summary_borer)  %>% summary()


# lm
lm(trans_incidence_borer ~ mean_rain, data = borer_joined_ev) %>% summary()

lm(incidence_borer ~ poly(mean_rain, 3, raw=T), data = borer_joined_ev) %>% summary()

lm(incidence_borer ~ mean_rain + mean_wind + mean_humid + mean_rain, data = borer_joined_ev) %>% summary()


borer_joined_ev %>%
  ggplot(aes(mean_temp, trans_incidence_borer)) +
  # geom_point() +
  geom_smooth(method="loess", se=FALSE)


borer_joined_ev %>%
  ggplot(aes(mean_wind, trans_incidence_borer)) +
  # geom_point() +
  geom_smooth(method="loess", se=FALSE)


borer_joined_ev %>%
  ggplot(aes(mean_humid, trans_incidence_borer)) +
  # geom_point() +
  geom_smooth(method="loess", se=FALSE)


borer_joined_ev %>%
  ggplot(aes(mean_rain, trans_incidence_borer)) +
  # geom_jitter(height = 0.04) +
  geom_smooth(method="loess", se=FALSE)
  # scale_y_log10()

detach("package:bestNormalize", unload = TRUE)
detach("package:nortest", unload = TRUE)
detach("package:MASS", unload = TRUE)
detach("package:stats", unload = TRUE)
detach("package:moments", unload = TRUE)
detach("package:car", unload = TRUE)
```

```Rating of 1 is classified as No damage to very slight```
```Corn Borer, Semi-looper, earworm```
```Semilooper```
```{r}
# Semilooper
semilooper_df_ev <- 
  insect_raw %>%
  select(FarmID, `Collection Date`, Province, Municipality, `Crop Stage`, Treatment, `Corn Type`, Variety, contains("Semi-looper - Damage Rating ")) %>%
  filter(Municipality != "Santa Rita" & Municipality != "Hilongos")

semilooper_df_ev$collect_date <- 
  as.Date(semilooper_df_ev$`Collection Date`, "%B %d, %Y")

semilooper_dmg_ev <-
  semilooper_df_ev %>% 
  mutate(Year = year(collect_date), Month = month(collect_date))

semilooper_joined_ev <-
  semilooper_dmg_ev %>% 
  left_join(monthly_averages, by=c('Year', 'Month')) %>%
  # # mutate_at(c(9:28), as.factor) %>%
  # mutate(across(contains("Semi-looper - Damage Rating "), 
  #        ~ case_when( . < 2 ~ "No",
  #                     . < 4 ~ "Light",
  #                     . < 6 ~ "Moderate",
  #                     . < 8 ~ "Severe",
  #                     . < 10 ~ "High"), 
  #        .names="Class_Infest_{.col}")) %>%
  # mutate(across(contains("Class_Infest_Semi-looper - Damage Rating "), ~classification_dmg(.))) %>%
  # # get the modal observation rating
  #  mutate(Modesemilooper_class_infest = getmode(c_across(contains("Class_Infest_Semi-looper - Damage Rating ")))) %>%
  # # create ranks column
  # mutate(semilooper_mode_classification = rank(Modesemilooper_class_infest))
  rowwise() %>%
    mutate(sum_no = sum(c_across(starts_with("Semi-looper - Damage Rating")) == "1"),
           sum_light = sum(c_across(starts_with("Semi-looper - Damage Rating")) == "3"),
           sum_moderate = sum(c_across(starts_with("Semi-looper - Damage Rating")) == "5"),
           sum_severe = sum(c_across(starts_with("Semi-looper - Damage Rating")) == "7"),
           sum_high = sum(c_across(starts_with("Semi-looper - Damage Rating")) == "9"),
           average_damage_semilooper = (((1 * sum_no) + (3 * sum_light) + (5 * sum_moderate) + (7 * sum_severe) + (9 * sum_high)) / (number_sampled_plants)),
           damage_rating_semilooper = (((1 * sum_no) + (3 * sum_light) + (5 * sum_moderate) + (7 * sum_severe) + (9 * sum_high)) / (number_sampled_plants * 9)) * percent_100,
           incidence_semilooper = ((sum(c_across(sum_light:sum_high))) * percent_100) / number_sampled_plants,
           )

View(semilooper_joined_ev)

summary_semilooper <-
  semilooper_joined_ev %>%
  group_by(Province, Municipality, `Corn Type`, Treatment) %>%
  remove_missing(na.rm=TRUE) %>%
  summarise(observations = n(),
            sum_avg_dmg_semilooper = sum(average_damage_semilooper),
            sum_dmg_rate_semilooper = sum(damage_rating_semilooper),
            sum_incidence_semilooper = sum(incidence_semilooper))

View(summary_semilooper)

summary_semilooper %>%
  ggplot(aes(sum_incidence_semilooper)) +
  geom_density()

summary_semilooper %>%
  ggplot(aes(sum_incidence_semilooper)) +
  geom_histogram()

summary_semilooper %>%
  ggplot(aes(sample=sum_incidence_semilooper)) +
  stat_qq() +
  stat_qq_line()

library("nortest")
library("moments")
library("stats")
library("MASS")
library("car")


ggqqplot(summary_semilooper$sum_incidence_semilooper)

# Kolmogorov Smirnov test for normality samples > 50
ks_test_semilooper <- ks.test(summary_semilooper$sum_incidence_semilooper, 'pnorm')

# Anderson-Darling Test is a goodness-of-fit test that determines 
# how well your data fits a given distribution. 
# This test is most typically used to see if your data follow a normal distribution or not.
# It is a modification of the Kolmogorov-Smirnov (K-S) test and 
# gives more weight to the tails than does the K-S test.
ad_test_semilooperlooper <- ad.test(summary_semilooper$sum_incidence_semilooper)

skew_semilooper <- skewness(summary_semilooper$sum_incidence_semilooper)
kurt_semilooper <- kurtosis(summary_semilooper$sum_incidence_semilooper)

# Jarque-Bera Normality Test performs a goodness-of-fit test that 
# determines whether or not sample data have skewness and 
# kurtosis that matches a normal distribution.
jarq_semilooper <- jarque.test(summary_semilooper$sum_incidence_semilooper)

# Bartlett’s test is used to test if k samples are from populations with equal variances. 
# Equal variances across populations are called homoscedasticity or homogeneity of variances.
bartlett_fertilizer_semilooper <- bartlett.test(sum_incidence_semilooper ~ Treatment, summary_semilooper)
bartlett_corntype_semilooper <- bartlett.test(sum_incidence_semilooper ~ `Corn Type`, summary_semilooper)
bartlett_municipality_semilooper <- bartlett.test(sum_incidence_semilooper ~ Municipality, summary_semilooper)
bartlett_province_semilooper <- bartlett.test(sum_incidence_semilooper ~ Province, summary_semilooper)
bartlett_fert_corn_semilooper <- bartlett.test(sum_incidence_semilooper ~ interaction(Treatment, `Corn Type`), summary_semilooper)


# Null hypothesis is variances across all samples are equal. 
# Levene’s test is an alternative to Bartlett’s test when the data is not normally distributed.
levenes_fertilizer_semilooper <- leveneTest(sum_incidence_semilooper ~ Treatment, summary_semilooper)
levenes_corntype_semilooper <- leveneTest(sum_incidence_semilooper ~ `Corn Type`, summary_semilooper)
levenes_municipality_semilooper <- leveneTest(sum_incidence_semilooper ~ Municipality, summary_semilooper)
levenes_province_semilooper <- leveneTest(sum_incidence_semilooper ~ Province, summary_semilooper)
levenes_fert_corn_semilooper <- leveneTest(sum_incidence_semilooper ~ interaction(Treatment, `Corn Type`), summary_semilooper)

summary_semilooper$order_treat <- ordered(summary_semilooper$Treatment,
                         levels = c("BRFR", "RFR", "ARFR"))

summary_semilooper$factor_corn <- factor(labels=c("N", "G"), levels=c("Non - GM Corn", "GM CORN"), summary_semilooper$`Corn Type`)

# AnOVa
aov_fert_semilooper <- aov(sum_incidence_semilooper ~ order_treat, summary_semilooper)
aov_corn_semilooper <- aov(sum_incidence_semilooper ~ factor_corn, summary_semilooper) 
ttest_corn_semilooper <- t.test(sum_incidence_semilooper ~ factor_corn, summary_semilooper)

# Two way AnOVa
twoway_fert_corn_semilooper <- aov(sum_incidence_semilooper ~ order_treat + factor_corn, summary_semilooper) 
tukey_fert_corn_semilooper <- TukeyHSD(twoway_fert_corn_semilooper)

# AnOVa with Interaction
aov_fert_corn_inter_semilooper <- aov(sum_incidence_semilooper ~ order_treat*factor_corn, summary_semilooper)
tukey_fert_corn_inter_semilooper <- TukeyHSD(aov_fert_corn_inter_semilooper)

aov_fert_semilooper %>% summary()
aov_corn_semilooper %>% summary()
ttest_corn_semilooper
twoway_fert_corn_semilooper %>% summary()
print(tukey_fert_corn_semilooper)
aov_fert_corn_inter_semilooper %>% summary()
print(tukey_fert_corn_inter_semilooper)

multcompLetters4(twoway_fert_corn_semilooper, tukey_fert_corn_semilooper)
multcompLetters4(aov_fert_corn_inter_semilooper, tukey_fert_corn_inter_semilooper)
# detach("package:onewaytests", unload = TRUE)

detach("package:nortest", unload = TRUE)
detach("package:moments", unload = TRUE)
detach("package:car", unload = TRUE)

# lm
lm(incidence_semilooper ~ mean_rain, data = semilooper_joined_ev) %>% summary()

lm(incidence_semilooper ~ poly(mean_rain, 3, raw=T), data = semilooper_joined_ev) %>% summary()

lm(incidence_semilooper ~ mean_rain + mean_wind + mean_humid + mean_rain, data = semilooper_joined_ev) %>% summary()


semilooper_joined_ev %>%
  ggplot(aes(mean_temp, incidence_semilooper)) +
  # geom_point() +
  geom_smooth(se=FALSE)
  # geom_vline(data = semilooper_joined_ev %>% filter(incidence_semilooper),
  #            aes(xintercept = mean_temp))

semilooper_joined_ev %>%
  ggplot(aes(mean_wind, incidence_semilooper)) +
  # geom_point() +
  geom_smooth(se=FALSE)


semilooper_joined_ev %>%
  ggplot(aes(mean_humid, incidence_semilooper)) +
  geom_smooth(se=FALSE)


semilooper_joined_ev %>%
  ggplot(aes(mean_rain, incidence_semilooper)) +
  geom_smooth(se=FALSE)

detach("package:MASS", unload = TRUE)
detach("package:stats", unload = TRUE)
```

```Rating of 1 is classified as No damage to very slight```
```Corn Borer, Semi-looper, earworm```
```Earworm```

```{r}
# Earworm
earworm_df_ev <- 
  insect_raw %>%
  select(FarmID, `Collection Date`, Province, Municipality, `Crop Stage`, Treatment, `Corn Type`, Variety, contains("Corn Earworm - Damage Rating ")) %>%
  filter(Municipality != "Santa Rita" & Municipality != "Hilongos")

earworm_df_ev$collect_date <- 
  as.Date(earworm_df_ev$`Collection Date`, "%B %d, %Y")

earworm_dmg_ev <-
  earworm_df_ev %>% 
  mutate(Year = year(collect_date), Month = month(collect_date))

earworm_joined_ev <-
  earworm_dmg_ev %>% 
  left_join(monthly_averages, by=c('Year', 'Month')) %>%
  # mutate_at(c(9:28), as.factor) %>%
  # mutate(across(contains("Corn Earworm - Damage Rating "), 
  #        ~ case_when( . < 2 ~ "No",
  #                     . < 4 ~ "Light",
  #                     . < 6 ~ "Moderate",
  #                     . < 8 ~ "Severe",
  #                     . < 10 ~ "High"), 
  #        .names="Class_Infest_{.col}")) %>%
  # mutate(across(contains("Class_Infest_Corn Earworm - Damage Rating "), ~classification_dmg(.))) %>%
  # # get the modal observation rating
  #  mutate(Modeearworm_class_infest = getmode(c_across(contains("Class_Infest_Corn Earworm - Damage Rating ")))) %>%
  # # create ranks column
  # mutate(earworm_mode_classification = rank(Modeearworm_class_infest))
rowwise() %>%
    mutate(sum_no = sum(c_across(starts_with("Corn Earworm - Damage Rating")) == "1"),
           sum_light = sum(c_across(starts_with("Corn Earworm - Damage Rating")) == "3"),
           sum_moderate = sum(c_across(starts_with("Corn Earworm - Damage Rating")) == "5"),
           sum_severe = sum(c_across(starts_with("Corn Earworm - Damage Rating")) == "7"),
           sum_high = sum(c_across(starts_with("Corn Earworm - Damage Rating")) == "9"),
           average_damage_earworm = (((1 * sum_no) + (3 * sum_light) + (5 * sum_moderate) + (7 * sum_severe) + (9 * sum_high)) / (number_sampled_plants)),
           damage_rating_earworm = (((1 * sum_no) + (3 * sum_light) + (5 * sum_moderate) + (7 * sum_severe) + (9 * sum_high)) / (number_sampled_plants * 9)) * percent_100,
           incidence_earworm = ((sum(c_across(sum_light:sum_high))) * percent_100) / number_sampled_plants,
           )

View(earworm_joined_ev)


summary_earworm <-
  earworm_joined_ev %>%
  group_by(Province, Municipality, `Corn Type`, Treatment) %>%
  remove_missing(na.rm=TRUE) %>%
  summarise(observations = n(),
            sum_avg_dmg_earworm = sum(average_damage_earworm),
            sum_dmg_rate_earworm = sum(damage_rating_earworm),
            sum_incidence_earworm = sum(incidence_earworm))

View(summary_earworm)

summary_earworm %>%
  ggplot(aes(sum_incidence_earworm)) +
  geom_density()

summary_earworm %>%
  ggplot(aes(sum_incidence_earworm)) +
  geom_histogram()

summary_earworm %>%
  ggplot(aes(sample=sum_incidence_earworm)) +
  stat_qq() +
  stat_qq_line()

library("nortest")
library("moments")
library("stats")
library("MASS")
library("car")
library("multcompView")

ggqqplot(summary_earworm$sum_incidence_earworm)

# Kolmogorov Smirnov test for normality samples > 50
ks_test_earworm <- ks.test(summary_earworm$sum_incidence_earworm, 'pnorm')

# Anderson-Darling Test is a goodness-of-fit test that determines how well your data fits a given distribution. 
# This test is most typically used to see if your data follow a normal distribution or not.
ad_test_earworm <- ad.test(summary_earworm$sum_incidence_earworm)

skew_earworm <- skewness(summary_earworm$sum_incidence_earworm)
kurt_earworm <- kurtosis(summary_earworm$sum_incidence_earworm)

# Jarque-Bera Normality Test performs a goodness-of-fit test that 
# determines whether or not sample data have skewness and 
# kurtosis that matches a normal distribution.
jarq_earworm <- jarque.test(summary_earworm$sum_incidence_earworm)

# Bartlett’s test is used to test if k samples are from populations with equal variances. 
# Equal variances across populations are called homoscedasticity or homogeneity of variances.
bartlett_fertilizer_earworm <- bartlett.test(sum_incidence_earworm ~ Treatment, summary_earworm)
bartlett_corntype_earworm <- bartlett.test(sum_incidence_earworm ~ `Corn Type`, summary_earworm)
bartlett_municipality_earworm <- bartlett.test(sum_incidence_earworm ~ Municipality, summary_earworm)
bartlett_province_earworm <- bartlett.test(sum_incidence_earworm ~ Province, summary_earworm)
bartlett_fert_corn_earworm <- bartlett.test(sum_incidence_earworm ~ interaction(Treatment, `Corn Type`), summary_earworm)


# Null hypothesis is variances across all samples are equal. 
# Levene’s test is an alternative to Bartlett’s test when the data is not normally distributed.
levenes_fertilizer_earworm <- leveneTest(sum_incidence_earworm ~ Treatment, summary_earworm)
levenes_corntype_earworm <- leveneTest(sum_incidence_earworm ~ `Corn Type`, summary_earworm)
levenes_municipality_earworm <- leveneTest(sum_incidence_earworm ~ Municipality, summary_earworm)
levenes_province_earworm <- leveneTest(sum_incidence_earworm ~ Province, summary_earworm)
levenes_fert_corn_earworm <- leveneTest(sum_incidence_earworm ~ interaction(Treatment, `Corn Type`), summary_earworm)


summary_earworm$order_treat <- ordered(summary_earworm$Treatment,
                         levels = c("BRFR", "RFR", "ARFR"))

summary_earworm$factor_corn <- factor(labels=c("N", "G"), levels=c("Non - GM Corn", "GM CORN"), summary_earworm$`Corn Type`)

# AnOVa
aov_fert_earworm <- aov(sum_incidence_earworm ~ order_treat, summary_earworm)
aov_corn_earworm <- aov(sum_incidence_earworm ~ factor_corn, summary_earworm) 
ttest_corn_earworm <- t.test(sum_incidence_earworm ~ factor_corn, summary_earworm)

# Two way AnOVa
twoway_fert_corn_earworm <- aov(sum_incidence_earworm ~ order_treat + factor_corn, summary_earworm) 
tukey_fert_corn_earworm <- TukeyHSD(twoway_fert_corn_earworm)

# AnOVa with Interaction
aov_fert_corn_inter_earworm <- aov(sum_incidence_earworm ~ order_treat*factor_corn, summary_earworm)
tukey_fert_corn_inter_earworm <- TukeyHSD(aov_fert_corn_inter_earworm)

aov_fert_earworm %>% summary()
aov_corn_earworm %>% summary()
ttest_corn_earworm
twoway_fert_corn_earworm %>% summary()
print(tukey_fert_corn_earworm)
aov_fert_corn_inter_earworm %>% summary()
print(tukey_fert_corn_inter_earworm)

twoway_fert_corn_earworm_letters <- multcompLetters4(twoway_fert_corn_earworm, tukey_fert_corn_earworm)
interaction_fert_corn_earworm_letters <- multcompLetters4(aov_fert_corn_inter_earworm, tukey_fert_corn_inter_earworm)
# detach("package:onewaytests", unload = TRUE)

detach("package:nortest", unload = TRUE)
detach("package:moments", unload = TRUE)
detach("package:car", unload = TRUE)

# lm
lm(incidence_earworm ~ mean_rain, data = earworm_joined_ev) %>% summary()

lm(incidence_earworm ~ poly(mean_rain, 3, raw=T), data = earworm_joined_ev) %>% summary()

lm(incidence_earworm ~ mean_rain + mean_wind + mean_humid + mean_rain, data = earworm_joined_ev) %>% summary()


earworm_joined_ev %>%
  ggplot(aes(mean_temp, incidence_earworm)) +
  # geom_point() +
  geom_smooth(se=FALSE)
  # geom_vline(data = earworm_joined_ev %>% filter(incidence_earworm),
  #            aes(xintercept = mean_temp))

earworm_joined_ev %>%
  ggplot(aes(mean_wind, incidence_earworm)) +
  # geom_point() +
  geom_smooth(se=FALSE)


earworm_joined_ev %>%
  ggplot(aes(mean_humid, incidence_earworm)) +
  geom_smooth(se=FALSE)


earworm_joined_ev %>%
  ggplot(aes(mean_rain, incidence_earworm)) +
  geom_smooth(se=FALSE)

detach("package:MASS", unload = TRUE)
detach("package:stats", unload = TRUE)

```

```Rating of 1 is classified as No damage or No infestation ONLY```
```Corn Planthopper, borer, Leaf feeders(Armyworm, cutworm)```
```rating of 1 is not included in computation on damage rating and incidence```
```Hopper```

```{r}
# Corn Plant Hopper
hopper_df_ev <- 
  insect_raw %>%
  select(FarmID, `Collection Date`, Province, Municipality, `Crop Stage`, Treatment, `Corn Type`, Variety, contains("Corn Plant Hopper - Damage Rating")) %>%
  filter(Municipality != "Santa Rita" & Municipality != "Hilongos")

# convert date format
hopper_df_ev$collect_date <- 
  as.Date(hopper_df_ev$`Collection Date`, "%B %d, %Y")

hopper_dmg_ev <-
  hopper_df_ev %>% 
  mutate(Year = year(collect_date), Month = month(collect_date))

# merged with monthly average weather parameters
classification_dmg <- function(x) {ordered(x, levels = c("No", "Light", "Moderate", "Severe", "High"))}

# 
# rank_rating <- c(1, 3, 5, 7, 9)
# names(rank_rating) <- c("No", "Light", "Moderate", "Severe", "High")
# ranked_class <- rank(rank_rating)
# factor(rank_rating, ordered=TRUE)
# 
# 
# getmode <- function(v) {
#   uniqv <- unique(v)
#   uniqv[which.max(tabulate(match(v, uniqv)))]
# }

hopper_joined_ev <-
  hopper_dmg_ev %>% 
  left_join(monthly_averages, by=c('Year', 'Month')) %>%
  # mutate_at(c(9:28), as.factor) %>%
  # mutate(across(contains("Corn Plant Hopper - Damage Rating "), 
  #        ~ case_when( . == 1 ~ "No",
  #                     . == 3 ~ "Light",
  #                     . == 5 ~ "Moderate",
  #                     . == 7 ~ "Severe",
  #                     . == 9 ~ "High"), 
  #        .names="Class_Infest_{.col}")) %>%
  # mutate(across(contains("Class_Infest_Corn Plant Hopper - Damage Rating "), ~classification_dmg(.))) %>%
  # # get the modal observation rating
  #  mutate(Mode_class_infest_hopper = getmode(c_across(contains("Class_Infest_Corn Plant Hopper - Damage Rating ")))) %>%
  # # create ranks column
  # mutate(Ranked_mode_classification = rank(Mode_class_infest_hopper)) %>%
  rowwise() %>%
  mutate(
             sum_no = sum(c_across(starts_with("Corn Plant Hopper - Damage Rating ")) == "1"),
             sum_light = sum(c_across(starts_with("Corn Plant Hopper - Damage Rating ")) == "3"),
             sum_moderate = sum(c_across(starts_with("Corn Plant Hopper - Damage Rating ")) == "5"),
             sum_severe = sum(c_across(starts_with("Corn Plant Hopper - Damage Rating ")) == "7"),
             sum_high = sum(c_across(starts_with("Corn Plant Hopper - Damage Rating ")) == "9"),
             average_damage_hopper = (((3 * sum_light) + (5 * sum_moderate) + (7 * sum_severe) + (9 * sum_high)) / (number_sampled_plants)),
             damage_rating_hopper = (((3 * sum_light) + (5 * sum_moderate) + (7 * sum_severe) + (9 * sum_high)) / (number_sampled_plants * 9)) * percent_100,
             incidence_hopper = ((sum(c_across(sum_light:sum_high))) * percent_100) / number_sampled_plants,
         )
         
View(hopper_joined_ev)

summary_hopper <-
  hopper_joined_ev %>%
  group_by(Province, Municipality, `Corn Type`, Treatment) %>%
  remove_missing(na.rm=TRUE) %>%
  summarise(observations = n(),
            sum_avg_dmg_hopper = sum(average_damage_hopper),
            sum_dmg_rate_hopper = sum(damage_rating_hopper),
            sum_incidence_hopper = sum(incidence_hopper))

View(summary_hopper)

summary_hopper %>%
  ggplot(aes(sum_incidence_hopper)) +
  geom_density()

summary_hopper %>%
  ggplot(aes(sum_incidence_hopper)) +
  geom_histogram()

summary_hopper %>%
  ggplot(aes(sample=sum_incidence_hopper)) +
  stat_qq() +
  stat_qq_line()

library("nortest")
library("moments")
library("stats")
library("MASS")
library("car")

ggqqplot(summary_hopper$sum_incidence_hopper)

# Kolmogorov Smirnov test for normality samples > 50
ks_test_hopper <- ks.test(summary_hopper$sum_incidence_hopper, 'pnorm')

# Anderson-Darling Test is a goodness-of-fit test that determines how well your data fits a given distribution. 
# This test is most typically used to see if your data follow a normal distribution or not.
ad_test_hopper <- ad.test(summary_hopper$sum_incidence_hopper)

skew_hopper <- skewness(summary_hopper$sum_incidence_hopper)
kurt_hopper <- kurtosis(summary_hopper$sum_incidence_hopper)

# Jarque-Bera Normality Test performs a goodness-of-fit test that 
# determines whether or not sample data have skewness and 
# kurtosis that matches a normal distribution.
jarq_hopper <- jarque.test(summary_hopper$sum_incidence_hopper)


# Bartlett’s test is used to test if k samples are from populations with equal variances. 
# Equal variances across populations are called homoscedasticity or homogeneity of variances.
bartlett_fertilizer_hopper <- bartlett.test(sum_incidence_hopper ~ Treatment, summary_hopper)
bartlett_corntype_hopper <- bartlett.test(sum_incidence_hopper ~ `Corn Type`, summary_hopper)
bartlett_municipality_hopper <- bartlett.test(sum_incidence_hopper ~ Municipality, summary_hopper)
bartlett_province_hopper <- bartlett.test(sum_incidence_hopper ~ Province, summary_hopper)
bartlett_fert_corn_hopper <- bartlett.test(sum_incidence_hopper ~ interaction(Treatment, `Corn Type`), summary_hopper)


# Null hypothesis is variances across all samples are equal. 
# Levene’s test is an alternative to Bartlett’s test when the data is not normally distributed.
levenes_fertilizer_hopper <- leveneTest(sum_incidence_hopper ~ Treatment, summary_hopper)
levenes_corntype_hopper <- leveneTest(sum_incidence_hopper ~ `Corn Type`, summary_hopper)
levenes_municipality_hopper <- leveneTest(sum_incidence_hopper ~ Municipality, summary_hopper)
levenes_province_hopper <- leveneTest(sum_incidence_hopper ~ Province, summary_hopper)
levenes_fert_corn_hopper <- leveneTest(sum_incidence_hopper ~ interaction(Treatment, `Corn Type`), summary_hopper)


summary_hopper$order_treat <- ordered(summary_hopper$Treatment,
                         levels = c("BRFR", "RFR", "ARFR"))

summary_hopper$factor_corn <- factor(labels=c("N", "G"), levels=c("Non - GM Corn", "GM CORN"), summary_hopper$`Corn Type`)

# AnOVa
aov_fert_hopper <- aov(sum_incidence_hopper ~ order_treat, summary_hopper)
aov_corn_hopper <- aov(sum_incidence_hopper ~ factor_corn, summary_hopper) 
ttest_corn_hopper <- t.test(sum_incidence_hopper ~ factor_corn, summary_hopper)

# Two way AnOVa
twoway_fert_corn_hopper <- aov(sum_incidence_hopper ~ order_treat + factor_corn, summary_hopper) 
tukey_fert_corn_hopper <- TukeyHSD(twoway_fert_corn_hopper)

# AnOVa with Interaction
aov_fert_corn_inter_hopper <- aov(sum_incidence_hopper ~ order_treat*factor_corn, summary_hopper)
tukey_fert_corn_inter_hopper <- TukeyHSD(aov_fert_corn_inter_hopper)

aov_fert_hopper %>% summary()
aov_corn_hopper %>% summary()
ttest_corn_hopper
twoway_fert_corn_hopper %>% summary()
print(tukey_fert_corn_hopper)
aov_fert_corn_inter_hopper %>% summary()
print(tukey_fert_corn_inter_hopper)

twoway_fert_corn_hopper_letters <- multcompLetters4(twoway_fert_corn_hopper, tukey_fert_corn_hopper)
interaction_fert_corn_hopper_letters <- multcompLetters4(aov_fert_corn_inter_hopper, tukey_fert_corn_inter_hopper)
# detach("package:onewaytests", unload = TRUE)

detach("package:nortest", unload = TRUE)
detach("package:moments", unload = TRUE)
detach("package:car", unload = TRUE)

# lm
lm(incidence_hopper ~ mean_rain, data = hopper_joined_ev) %>% summary()

lm(incidence_hopper ~ poly(mean_rain, 3, raw=T), data = hopper_joined_ev) %>% summary()

lm(incidence_hopper ~ mean_rain + mean_wind + mean_humid + mean_rain, data = hopper_joined_ev) %>% summary()


hopper_joined_ev %>%
  ggplot(aes(mean_temp, incidence_hopper)) +
  # geom_point() +
  geom_smooth(se=FALSE)
  # geom_vline(data = hopper_joined_ev %>% filter(incidence_hopper),
  #            aes(xintercept = mean_temp))

hopper_joined_ev %>%
  ggplot(aes(mean_wind, incidence_hopper)) +
  # geom_point() +
  geom_smooth(se=FALSE)


hopper_joined_ev %>%
  ggplot(aes(mean_humid, incidence_hopper)) +
  geom_smooth(se=FALSE)


hopper_joined_ev %>%
  ggplot(aes(mean_rain, incidence_hopper)) +
  geom_smooth(se=FALSE)

detach("package:MASS", unload = TRUE)
detach("package:stats", unload = TRUE)
```

```Rating of 1 is classified as No damage or No infestation ONLY```
```Corn Planthopper, borer, Leaf feeders(Armyworm, `cutworm`)```
```rating of 1 is not included in computation on damage rating and incidence```
```Cutworm```
```{r}
# Corn leaf feeders: Cutworm
cutworm_df_ev <- 
  insect_raw %>%
  select(FarmID, `Collection Date`, Province, Municipality, `Crop Stage`, Treatment, `Corn Type`, Variety, contains("Cutworm - Damage Rating ")) %>%
  filter(Municipality != "Santa Rita" & Municipality != "Hilongos")

cutworm_df_ev$collect_date <- 
  as.Date(cutworm_df_ev$`Collection Date`, "%B %d, %Y")

cutworm_dmg_ev <-
  cutworm_df_ev %>% 
  mutate(Year = year(collect_date), Month = month(collect_date))

number_sampled_plants <- 20


cutworm_joined_ev <-
  cutworm_dmg_ev %>% 
  left_join(monthly_averages, by=c('Year', 'Month')) %>%
  # mutate_at(c(9:28), as.factor) %>%
  rowwise() %>%
    mutate(sum_no = sum(c_across(starts_with("Cutworm - Damage Rating ")) == "1"),
           sum_light = sum(c_across(starts_with("Cutworm - Damage Rating ")) == "3"),
           sum_moderate = sum(c_across(starts_with("Cutworm - Damage Rating ")) == "5"),
           sum_severe = sum(c_across(starts_with("Cutworm - Damage Rating ")) == "7"),
           sum_high = sum(c_across(starts_with("Cutworm - Damage Rating ")) == "9"),
           average_damage_cutworm = (((1 * sum_no) + (3 * sum_light) + (5 * sum_moderate) + (7 * sum_severe) + (9 * sum_high)) / (number_sampled_plants)),
           damage_rating_cutworm = (((1 * sum_no) + (3 * sum_light) + (5 * sum_moderate) + (7 * sum_severe) + (9 * sum_high)) / (number_sampled_plants * 9)) * percent_100,
           incidence_cutworm = ((sum(c_across(sum_light:sum_high))) * percent_100) / number_sampled_plants,
           )

View(cutworm_joined_ev)


summary_cutworm <-
  cutworm_joined_ev %>%
  group_by(Province, Municipality, `Corn Type`, Treatment) %>%
  filter(Municipality != "Santa Rita" & Municipality != "Hilongos") %>%
  remove_missing(na.rm=TRUE) %>%
  summarise(sum_avg_dmg_cutworm = sum(average_damage_cutworm),
            sum_dmg_rate_cutworm = sum(damage_rating_cutworm),
            sum_incidence_cutworm = sum(incidence_cutworm))

View(summary_cutworm)


summary_cutworm <-
  cutworm_joined_ev %>%
  group_by(Province, Municipality, `Corn Type`, Treatment) %>%
  remove_missing(na.rm=TRUE) %>%
  summarise(observations = n(),
            sum_avg_dmg_cutworm = sum(average_damage_cutworm),
            sum_dmg_rate_cutworm = sum(damage_rating_cutworm),
            sum_incidence_cutworm = sum(incidence_cutworm))

View(summary_cutworm)


summary_cutworm %>%
  ggplot(aes(sum_incidence_cutworm)) +
  geom_density()

summary_cutworm %>%
  ggplot(aes(sum_incidence_cutworm)) +
  geom_histogram()

summary_cutworm %>%
  ggplot(aes(sample=sum_incidence_cutworm)) +
  stat_qq() +
  stat_qq_line()

library("nortest")
library("moments")
library("stats")
library("MASS")
library("car")

ggqqplot(summary_cutworm$sum_incidence_cutworm)

# Kolmogorov Smirnov test for normality samples > 50
ks_test_cutworm <- ks.test(summary_cutworm$sum_incidence_cutworm, 'pnorm')

# Anderson-Darling Test is a goodness-of-fit test that determines how well your data fits a given distribution. 
# This test is most typically used to see if your data follow a normal distribution or not.
ad_test_cutworm <- ad.test(summary_cutworm$sum_incidence_cutworm)

skew_cutworm <- skewness(summary_cutworm$sum_incidence_cutworm)
kurt_cutworm <- kurtosis(summary_cutworm$sum_incidence_cutworm)

# Jarque-Bera Normality Test performs a goodness-of-fit test that 
# determines whether or not sample data have skewness and 
# kurtosis that matches a normal distribution.
jarq_cutworm <- jarque.test(summary_cutworm$sum_incidence_cutworm)

# Null hypothesis is variances across all samples are equal. 
# Levene’s test is an alternative to Bartlett’s test when the data is not normally distributed.
levenes_fertilizer_cutworm <- leveneTest(sum_incidence_cutworm ~ Treatment, summary_cutworm)
levenes_corntype_cutworm <- leveneTest(sum_incidence_cutworm ~ `Corn Type`, summary_cutworm)
levenes_municipality_cutworm <- leveneTest(sum_incidence_cutworm ~ Municipality, summary_cutworm)
levenes_province_cutworm <- leveneTest(sum_incidence_cutworm ~ Province, summary_cutworm)
levenes_fert_corn_cutworm <- leveneTest(sum_incidence_cutworm ~ interaction(Treatment, `Corn Type`), summary_cutworm)



summary_cutworm$order_treat <- ordered(summary_cutworm$Treatment,
                         levels = c("BRFR", "RFR", "ARFR"))

summary_cutworm$factor_corn <- factor(labels=c("N", "G"), levels=c("Non - GM Corn", "GM CORN"), summary_cutworm$`Corn Type`)

# AnOVa
aov_fert_cutworm <- aov(sum_incidence_cutworm ~ order_treat, summary_cutworm)
aov_corn_cutworm <- aov(sum_incidence_cutworm ~ factor_corn, summary_cutworm) 
ttest_corn_cutworm <- t.test(sum_incidence_cutworm ~ factor_corn, summary_cutworm)

# Two way AnOVa
twoway_fert_corn_cutworm <- aov(sum_incidence_cutworm ~ order_treat + factor_corn, summary_cutworm) 
tukey_fert_corn_cutworm <- TukeyHSD(twoway_fert_corn_cutworm)

# AnOVa with Interaction
aov_fert_corn_inter_cutworm <- aov(sum_incidence_cutworm ~ order_treat*factor_corn, summary_cutworm)
tukey_fert_corn_inter_cutworm <- TukeyHSD(aov_fert_corn_inter_cutworm)

aov_fert_cutworm %>% summary()
aov_corn_cutworm %>% summary()
ttest_corn_cutworm
twoway_fert_corn_cutworm %>% summary()
print(tukey_fert_corn_cutworm)
aov_fert_corn_inter_cutworm %>% summary()
print(tukey_fert_corn_inter_cutworm)

twoway_fert_corn_cutworm_letters <- multcompLetters4(twoway_fert_corn_cutworm, tukey_fert_corn_cutworm)
interaction_fert_corn_cutworm_letters <- multcompLetters4(aov_fert_corn_inter_cutworm, tukey_fert_corn_inter_cutworm)
# detach("package:onewaytests", unload = TRUE)

detach("package:nortest", unload = TRUE)
detach("package:moments", unload = TRUE)
detach("package:car", unload = TRUE)

# lm
lm(incidence_cutworm ~ mean_rain, data = cutworm_joined_ev) %>% summary()

lm(incidence_cutworm ~ poly(mean_rain, 3, raw=T), data = cutworm_joined_ev) %>% summary()

lm(incidence_cutworm ~ mean_rain + mean_wind + mean_humid + mean_rain, data = cutworm_joined_ev) %>% summary()


cutworm_joined_ev %>%
  ggplot(aes(mean_temp, incidence_cutworm)) +
  # geom_point() +
  geom_smooth(se=FALSE)
  # geom_vline(data = cutworm_joined_ev %>% filter(incidence_cutworm),
  #            aes(xintercept = mean_temp))

cutworm_joined_ev %>%
  ggplot(aes(mean_wind, incidence_cutworm)) +
  # geom_point() +
  geom_smooth(se=FALSE)


cutworm_joined_ev %>%
  ggplot(aes(mean_humid, incidence_cutworm)) +
  geom_smooth(se=FALSE)


cutworm_joined_ev %>%
  ggplot(aes(mean_rain, incidence_cutworm)) +
  geom_smooth(se=FALSE)

detach("package:MASS", unload = TRUE)
detach("package:stats", unload = TRUE)

```

```Rating of 1 is classified as No damage or No infestation ONLY```
```Corn Planthopper, aphids, Leaf feeders(Armyworm, cutworm)```
```rating of 1 is not included in computation on damage rating and incidence```
```Armyworm```

```{r}
# Corn leaf feeders: Armyworm
armyworm_df_ev <- 
  insect_raw %>%
  select(FarmID, `Collection Date`, Province, Municipality, `Crop Stage`, Treatment, `Corn Type`, Variety, starts_with("Armyworm - Damage Rating ")) %>%
  filter(Municipality != "Santa Rita" & Municipality != "Hilongos")

armyworm_df_ev$collect_date <- 
  as.Date(armyworm_df_ev$`Collection Date`, "%B %d, %Y")

armyworm_dmg_ev <-
  armyworm_df_ev %>% 
  mutate(Year = year(collect_date), Month = month(collect_date))

number_sampled_plants <- 20


armyworm_joined_ev <-
  armyworm_dmg_ev %>% 
  left_join(monthly_averages, by=c('Year', 'Month')) %>%
  # mutate_at(c(9:28), as.factor) %>%
  rowwise() %>%
    mutate(sum_no = sum(c_across(starts_with("Armyworm - Damage Rating ")) == "1"),
           sum_light = sum(c_across(starts_with("Armyworm - Damage Rating ")) == "3"),
           sum_moderate = sum(c_across(starts_with("Armyworm - Damage Rating ")) == "5"),
           sum_severe = sum(c_across(starts_with("Armyworm - Damage Rating ")) == "7"),
           sum_high = sum(c_across(starts_with("Armyworm - Damage Rating ")) == "9"),
           average_damage_armyworm = (((1 * sum_no) + (3 * sum_light) + (5 * sum_moderate) + (7 * sum_severe) + (9 * sum_high)) / (number_sampled_plants)),
           damage_rating_armyworm = (((1 * sum_no) + (3 * sum_light) + (5 * sum_moderate) + (7 * sum_severe) + (9 * sum_high)) / (number_sampled_plants * 9)) * percent_100,
           incidence_armyworm = ((sum(c_across(sum_light:sum_high))) * percent_100) / number_sampled_plants,
           )

View(armyworm_joined_ev)

summary_armyworm <-
  armyworm_joined_ev %>%
  group_by(Province, Municipality, `Corn Type`, Treatment) %>%
  remove_missing(na.rm=TRUE) %>%
  summarise(sum_avg_dmg_armyworm = sum(average_damage_armyworm),
            sum_dmg_rate_armyworm = sum(damage_rating_armyworm),
            sum_incidence_armyworm = sum(incidence_armyworm))

View(summary_armyworm)


summary_armyworm %>%
  ggplot(aes(sum_incidence_armyworm)) +
  geom_density()

summary_armyworm %>%
  ggplot(aes(sum_incidence_armyworm)) +
  geom_histogram()

summary_armyworm %>%
  ggplot(aes(sample=sum_incidence_armyworm)) +
  stat_qq() +
  stat_qq_line()

library("nortest")
library("moments")
library("stats")
library("MASS")
library("car")

ggqqplot(summary_armyworm$sum_incidence_armyworm)

# Kolmogorov Smirnov test for normality samples > 50
ks_test_armyworm <- ks.test(summary_armyworm$sum_incidence_armyworm, 'pnorm')

# Anderson-Darling Test is a goodness-of-fit test that determines how well your data fits a given distribution. 
# This test is most typically used to see if your data follow a normal distribution or not.
ad_test_armyworm <- ad.test(summary_armyworm$sum_incidence_armyworm)

skew_armyworm <- skewness(summary_armyworm$sum_incidence_armyworm)
kurt_armyworm <- kurtosis(summary_armyworm$sum_incidence_armyworm)

# Jarque-Bera Normality Test performs a goodness-of-fit test that 
# determines whether or not sample data have skewness and 
# kurtosis that matches a normal distribution.
jarq_armyworm <- jarque.test(summary_armyworm$sum_incidence_armyworm)

# Null hypothesis is variances across all samples are equal. 
# Levene’s test is an alternative to Bartlett’s test when the data is not normally distributed.
levenes_fertilizer_armyworm <- leveneTest(sum_incidence_armyworm ~ Treatment, summary_armyworm)
levenes_corntype_armyworm <- leveneTest(sum_incidence_armyworm ~ `Corn Type`, summary_armyworm)
levenes_municipality_armyworm <- leveneTest(sum_incidence_armyworm ~ Municipality, summary_armyworm)
levenes_province_armyworm <- leveneTest(sum_incidence_armyworm ~ Province, summary_armyworm)
levenes_fert_corn_armyworm <- leveneTest(sum_incidence_armyworm ~ interaction(Treatment, `Corn Type`), summary_armyworm)


summary_armyworm$order_treat <- ordered(summary_armyworm$Treatment,
                         levels = c("BRFR", "RFR", "ARFR"))

summary_armyworm$factor_corn <- factor(labels=c("N", "G"), levels=c("Non - GM Corn", "GM CORN"), summary_armyworm$`Corn Type`)

# AnOVa
aov_fert_armyworm <- aov(sum_incidence_armyworm ~ order_treat, summary_armyworm)
ttest_corn_armyworm <- t.test(sum_incidence_armyworm ~ factor_corn, summary_armyworm)

# Kruskall-Wallis on corn type
kruskall_corn_armyworm <- kruskal.test(sum_incidence_armyworm ~ factor_corn, summary_armyworm)

# Two way AnOVa
twoway_fert_corn_armyworm <- aov(sum_incidence_armyworm ~ order_treat + factor_corn, summary_armyworm) 
tukey_fert_corn_armyworm <- TukeyHSD(twoway_fert_corn_armyworm)

# AnOVa with Interaction
aov_fert_corn_inter_armyworm <- aov(sum_incidence_armyworm ~ order_treat*factor_corn, summary_armyworm)
tukey_fert_corn_inter_armyworm <- TukeyHSD(aov_fert_corn_inter_armyworm)

aov_fert_armyworm %>% summary()

ttest_corn_armyworm
twoway_fert_corn_armyworm %>% summary()
kruskall_corn_armyworm
print(tukey_fert_corn_armyworm)
aov_fert_corn_inter_armyworm %>% summary()
print(tukey_fert_corn_inter_armyworm)

twoway_fert_corn_armyworm_letters <- multcompLetters4(twoway_fert_corn_armyworm, tukey_fert_corn_armyworm)
interaction_fert_corn_armyworm_letters <- multcompLetters4(aov_fert_corn_inter_armyworm, tukey_fert_corn_inter_armyworm)
# detach("package:onewaytests", unload = TRUE)

detach("package:nortest", unload = TRUE)
detach("package:moments", unload = TRUE)
detach("package:car", unload = TRUE)

# lm
lm(incidence_armyworm ~ mean_rain, data = armyworm_joined_ev) %>% summary()

lm(incidence_armyworm ~ poly(mean_rain, 3, raw=T), data = armyworm_joined_ev) %>% summary()

lm(incidence_armyworm ~ mean_rain + mean_wind + mean_humid + mean_rain, data = armyworm_joined_ev) %>% summary()


armyworm_joined_ev %>%
  ggplot(aes(mean_temp, incidence_armyworm)) +
  # geom_point() +
  geom_smooth(se=FALSE)
  # geom_vline(data = armyworm_joined_ev %>% filter(incidence_armyworm),
  #            aes(xintercept = mean_temp))

armyworm_joined_ev %>%
  ggplot(aes(mean_wind, incidence_armyworm)) +
  # geom_point() +
  geom_smooth(se=FALSE)


armyworm_joined_ev %>%
  ggplot(aes(mean_humid, incidence_armyworm)) +
  geom_smooth(se=FALSE)


armyworm_joined_ev %>%
  ggplot(aes(mean_rain, incidence_armyworm)) +
  geom_smooth(se=FALSE)

detach("package:MASS", unload = TRUE)
detach("package:stats", unload = TRUE)
```

```Rating of 1 is classified as No damage or No infestation ONLY```
```Corn Planthopper, aphids, Leaf feeders(Armyworm, cutworm)```
```rating of 1 is not included in computation on damage rating and incidence```
```Aphids```

```{r}
# Aphids
aphids_df_ev <- 
  insect_raw %>%
  select(FarmID, `Collection Date`, Province, Municipality, `Crop Stage`, Treatment, `Corn Type`, Variety, starts_with("Aphids - Damage Rating ")) %>%
  filter(Municipality != "Santa Rita" & Municipality != "Hilongos") 

aphids_df_ev$collect_date <- 
  as.Date(aphids_df_ev$`Collection Date`, "%B %d, %Y")

aphids_dmg_ev <-
  aphids_df_ev %>% 
  mutate(Year = year(collect_date), Month = month(collect_date))


aphids_joined_ev <-
  aphids_dmg_ev %>% 
  left_join(monthly_averages, by=c('Year', 'Month')) %>%
  # mutate_at(c(9:28), as.factor) %>%
  rowwise() %>%
    mutate(sum_no = sum(c_across(starts_with("Aphids - Damage Rating ")) == "1"),
           sum_light = sum(c_across(starts_with("Aphids - Damage Rating ")) == "3"),
           sum_moderate = sum(c_across(starts_with("Aphids - Damage Rating ")) == "5"),
           sum_severe = sum(c_across(starts_with("Aphids - Damage Rating ")) == "7"),
           sum_high = sum(c_across(starts_with("Aphids - Damage Rating ")) == "9"),
           average_damage_aphids = ((1 * sum_no) + (3 * sum_light) + (5 * sum_moderate) + (7 * sum_severe) + (9 * sum_high)) / (number_sampled_plants),
           damage_rating_aphids = (((1 * sum_no) + (3 * sum_light) + (5 * sum_moderate) + (7 * sum_severe) + (9 * sum_high)) / (number_sampled_plants * 9)) * percent_100,
           incidence_aphids = ((sum(c_across(sum_light:sum_high))) * percent_100) / number_sampled_plants,
           )

View(aphids_joined_ev)

summary_aphids <-
  aphids_joined_ev %>%
  group_by(Province, Municipality, `Corn Type`, Treatment) %>%
  remove_missing(na.rm=TRUE) %>%
  summarise(sum_avg_dmg_aphids = sum(average_damage_aphids),
            sum_dmg_rate_aphids = sum(damage_rating_aphids),
            sum_incidence_aphids = sum(incidence_aphids))

View(summary_aphids)


summary_aphids %>%
  ggplot(aes(sum_incidence_aphids)) +
  geom_density()

summary_aphids %>%
  ggplot(aes(sum_incidence_aphids)) +
  geom_histogram()

summary_aphids %>%
  ggplot(aes(sample=sum_incidence_aphids)) +
  stat_qq() +
  stat_qq_line()

library("nortest")
library("moments")
library("stats")
library("MASS")
library("car")
library("cellWise")

ggqqplot(summary_aphids$sum_incidence_aphids)

# Kolmogorov Smirnov test for normality samples > 50
ks_test_aphids <- ks.test(summary_aphids$sum_incidence_aphids, 'pnorm')

# Anderson-Darling Test is a goodness-of-fit test that determines how well your data fits a given distribution. 
# This test is most typically used to see if your data follow a normal distribution or not.
ad_test_aphids <- ad.test(summary_aphids$sum_incidence_aphids)

skew_aphids <- skewness(summary_aphids$sum_incidence_aphids)
kurt_aphids <- kurtosis(summary_aphids$sum_incidence_aphids)

# Jarque-Bera Normality Test performs a goodness-of-fit test that 
# determines whether or not sample data have skewness and 
# kurtosis that matches a normal distribution.
jarq_aphids <- jarque.test(summary_aphids$sum_incidence_aphids)

# Null hypothesis is variances across all samples are equal. 
# Levene’s test is an alternative to Bartlett’s test when the data is not normally distributed.
levenes_fertilizer_aphids <- leveneTest(sum_incidence_aphids ~ Treatment, summary_aphids)
levenes_corntype_aphids <- leveneTest(sum_incidence_aphids ~ `Corn Type`, summary_aphids)
levenes_municipality_aphids <- leveneTest(sum_incidence_aphids ~ Municipality, summary_aphids)
levenes_province_aphids <- leveneTest(sum_incidence_aphids ~ Province, summary_aphids)
levenes_fert_corn_aphids <- leveneTest(sum_incidence_aphids ~ interaction(Treatment, `Corn Type`), summary_aphids)



summary_aphids$order_treat <- ordered(summary_aphids$Treatment,
                         levels = c("BRFR", "RFR", "ARFR"))

summary_aphids$factor_corn <- factor(labels=c("N", "G"), levels=c("Non - GM Corn", "GM CORN"), summary_aphids$`Corn Type`)

# AnOVa
aov_fert_aphids <- aov(sum_incidence_aphids ~ order_treat, summary_aphids)
ttest_corn_aphids <- t.test(sum_incidence_aphids ~ factor_corn, summary_aphids)

# Kruskall-Wallis on corn type
kruskall_corn_aphids <- kruskal.test(sum_incidence_aphids ~ factor_corn, summary_aphids)

# Two way AnOVa
twoway_fert_corn_aphids <- aov(sum_incidence_aphids ~ order_treat + factor_corn, summary_aphids) 
tukey_fert_corn_aphids <- TukeyHSD(twoway_fert_corn_aphids)

# AnOVa with Interaction
aov_fert_corn_inter_aphids <- aov(sum_incidence_aphids ~ order_treat*factor_corn, summary_aphids)
tukey_fert_corn_inter_aphids <- TukeyHSD(aov_fert_corn_inter_aphids)

aov_fert_aphids %>% summary()
ttest_corn_aphids
twoway_fert_corn_aphids %>% summary()
kruskall_corn_aphids
print(tukey_fert_corn_aphids)
aov_fert_corn_inter_aphids %>% summary()
print(tukey_fert_corn_inter_aphids)

twoway_fert_corn_aphids_letters <- multcompLetters4(twoway_fert_corn_aphids, tukey_fert_corn_aphids)
interaction_fert_corn_aphids_letters <- multcompLetters4(aov_fert_corn_inter_aphids, tukey_fert_corn_inter_aphids)
# detach("package:onewaytests", unload = TRUE)

detach("package:nortest", unload = TRUE)
detach("package:moments", unload = TRUE)
detach("package:car", unload = TRUE)

# lm
lm(incidence_aphids ~ mean_rain, data = aphids_joined_ev) %>% summary()

lm(incidence_aphids ~ poly(mean_rain, 3, raw=T), data = aphids_joined_ev) %>% summary()

lm(incidence_aphids ~ mean_rain + mean_wind + mean_humid + mean_rain, data = aphids_joined_ev) %>% summary()


aphids_joined_ev %>%
  ggplot(aes(mean_temp, incidence_aphids)) +
  # geom_point() +
  geom_smooth(se=FALSE)
  # geom_vline(data = aphids_joined_ev %>% filter(incidence_aphids),
  #            aes(xintercept = mean_temp))

aphids_joined_ev %>%
  ggplot(aes(mean_wind, incidence_aphids)) +
  # geom_point() +
  geom_smooth(se=FALSE)


aphids_joined_ev %>%
  ggplot(aes(mean_humid, incidence_aphids)) +
  geom_smooth(se=FALSE)


aphids_joined_ev %>%
  ggplot(aes(mean_rain, incidence_aphids)) +
  geom_smooth(se=FALSE)

detach("package:MASS", unload = TRUE)
```


```Fall armyworm has different rating scale (according to dashboard)```

```{r}
# Fall Armyworm
faw_df_ev <- 
  insect_raw %>%
  select(FarmID, `Collection Date`, Province, Municipality, `Crop Stage`, Treatment, `Corn Type`, Variety, contains("Fall Armyworm - Damage Rating"))%>%
  filter(Municipality != "Santa Rita" & Municipality != "Hilongos") 

faw_df_ev$collect_date <- 
  as.Date(faw_df_ev$`Collection Date`, "%B %d, %Y")

faw_dmg_ev <-
  faw_df_ev %>% 
  mutate(Year = year(collect_date), Month = month(collect_date))

faw_joined_ev <-
  faw_dmg_ev %>% 
  left_join(monthly_averages, by=c('Year', 'Month')) %>%
  rowwise() %>%
  mutate(sum_0 = sum(c_across(starts_with("Fall Armyworm - Damage Rating ")) == "0"),
         sum_1 = sum(c_across(starts_with("Fall Armyworm - Damage Rating ")) == "1"),
         sum_2 = sum(c_across(starts_with("Fall Armyworm - Damage Rating ")) == "2"),
         sum_3 = sum(c_across(starts_with("Fall Armyworm - Damage Rating ")) == "3"),
         sum_4 = sum(c_across(starts_with("Fall Armyworm - Damage Rating ")) == "4"),
         sum_5 = sum(c_across(starts_with("Fall Armyworm - Damage Rating ")) == "5"),
         sum_6 = sum(c_across(starts_with("Fall Armyworm - Damage Rating ")) == "6"),
         sum_7 = sum(c_across(starts_with("Fall Armyworm - Damage Rating ")) == "7"),
         sum_8 = sum(c_across(starts_with("Fall Armyworm - Damage Rating ")) == "8"),
         sum_9 = sum(c_across(starts_with("Fall Armyworm - Damage Rating ")) == "9"),
         average_damage_faw = (((1 * sum_1) + (3 * sum_3) + (5 * sum_5) + (7 * sum_7) + (9 * sum_9) + (2 * sum_2) + (4 * sum_4) + (6 * sum_6) + (8 * sum_8)) / (number_sampled_plants)),
         damage_rating_faw = (((1 * sum_1) + (3 * sum_3) + (5 * sum_5) + (7 * sum_7) + (9 * sum_9) + (2 * sum_2) + (4 * sum_4) + (6 * sum_6) + (8 * sum_8)) / (number_sampled_plants * 9)) * percent_100,
         incidence_faw = ((sum(c_across(sum_1:sum_9)))* percent_100) / number_sampled_plants,
         )

View(faw_joined_ev)

summary_faw <-
  faw_joined_ev %>%
  group_by(Province, Municipality, `Corn Type`, Treatment) %>%
  remove_missing(na.rm=TRUE) %>%
  summarise(sum_avg_dmg_faw = sum(average_damage_faw),
            sum_dmg_rate_faw = sum(damage_rating_faw),
            sum_incidence_faw = sum(incidence_faw))

View(summary_faw)

summary_faw %>%
  ggplot(aes(sum_incidence_faw)) +
  geom_density()

summary_faw %>%
  ggplot(aes(sum_incidence_faw)) +
  geom_histogram()

summary_faw %>%
  ggplot(aes(sample=sum_incidence_faw)) +
  stat_qq() +
  stat_qq_line()

library("nortest")
library("moments")
library("stats")
library("car")
library("MASS")

ggqqplot(summary_faw$sum_incidence_faw)

# Kolmogorov Smirnov test for normality samples > 50
ks_test_faw <- ks.test(summary_faw$sum_incidence_faw, 'pnorm')

# Anderson-Darling Test is a goodness-of-fit test that determines how well your data fits a given distribution. 
# This test is most typically used to see if your data follow a normal distribution or not.
ad_test_faw <- ad.test(summary_faw$sum_incidence_faw)

skew_faw <- skewness(summary_faw$sum_incidence_faw)
kurt_faw <- kurtosis(summary_faw$sum_incidence_faw)

# Jarque-Bera Normality Test performs a goodness-of-fit test that 
# determines whether or not sample data have skewness and 
# kurtosis that matches a normal distribution.
jarq_faw <- jarque.test(summary_faw$sum_incidence_faw)


# Null hypothesis is variances across all samples are equal. 
# Levene’s test is an alternative to Bartlett’s test when the data is not normally distributed.
levenes_fertilizer_faw <- leveneTest(sum_incidence_faw ~ Treatment, summary_faw)
levenes_corntype_faw <- leveneTest(sum_incidence_faw ~ `Corn Type`, summary_faw)
levenes_municipality_faw <- leveneTest(sum_incidence_faw ~ Municipality, summary_faw)
levenes_province_faw <- leveneTest(sum_incidence_faw ~ Province, summary_faw)
levenes_fert_corn_faw <- leveneTest(sum_incidence_faw ~ interaction(Treatment, `Corn Type`), summary_faw)


summary_faw$order_treat <- ordered(summary_faw$Treatment,
                         levels = c("BRFR", "RFR", "ARFR"))

summary_faw$factor_corn <- factor(labels=c("N", "G"), levels=c("Non - GM Corn", "GM CORN"), summary_faw$`Corn Type`)

# AnOVa
aov_fert_faw <- aov(sum_incidence_faw ~ order_treat, summary_faw)
aov_corn_faw <- aov(sum_incidence_faw ~ factor_corn, summary_faw)

ttest_corn_faw <- t.test(sum_incidence_faw ~ factor_corn, summary_faw)

# # Kruskall-Wallis on corn type
# kruskall_corn_faw <- kruskal.test(sum_incidence_faw ~ factor_corn, summary_faw)

# Two way AnOVa
twoway_fert_corn_faw <- aov(sum_incidence_faw ~ order_treat + factor_corn, summary_faw) 
tukey_fert_corn_faw <- TukeyHSD(twoway_fert_corn_faw)

# AnOVa with Interaction
aov_fert_corn_inter_faw <- aov(sum_incidence_faw ~ order_treat*factor_corn, summary_faw)
tukey_fert_corn_inter_faw <- TukeyHSD(aov_fert_corn_inter_faw)


# Results print
aov_fert_faw %>% summary()
ttest_corn_faw
aov_corn_faw %>% summary()

twoway_fert_corn_faw %>% summary()
kruskall_corn_faw
print(tukey_fert_corn_faw)
aov_fert_corn_inter_faw %>% summary()
print(tukey_fert_corn_inter_faw)

twoway_fert_corn_faw_letters <- multcompLetters4(twoway_fert_corn_faw, tukey_fert_corn_faw)
interaction_fert_corn_faw_letters <- multcompLetters4(aov_fert_corn_inter_faw, tukey_fert_corn_inter_faw)
# detach("package:onewaytests", unload = TRUE)

detach("package:nortest", unload = TRUE)
detach("package:moments", unload = TRUE)
detach("package:car", unload = TRUE)

# lm
lm(incidence_faw ~ mean_rain, data = faw_joined_ev) %>% summary()

lm(incidence_faw ~ poly(mean_rain, 3, raw=T), data = faw_joined_ev) %>% summary()

lm(incidence_faw ~ mean_rain + mean_wind + mean_humid + mean_rain, data = faw_joined_ev) %>% summary()


faw_joined_ev %>%
  ggplot(aes(mean_temp, incidence_faw)) +
  # geom_point() +
  geom_smooth(se=FALSE)
  # geom_vline(data = faw_joined_ev %>% filter(incidence_faw),
  #            aes(xintercept = mean_temp))

faw_joined_ev %>%
  ggplot(aes(mean_wind, incidence_faw)) +
  # geom_point() +
  geom_smooth(se=FALSE)


faw_joined_ev %>%
  ggplot(aes(mean_humid, incidence_faw)) +
  geom_smooth(se=FALSE)


faw_joined_ev %>%
  ggplot(aes(mean_rain, incidence_faw)) +
  geom_smooth(se=FALSE)

detach("package:MASS", unload = TRUE)

```

```{r}

# faw
faw_ev <-
  faw_joined_ev %>%
  mutate(Province = factor(Province),
         Municipality = factor(Municipality),
         crop_stage = factor(`Crop Stage`),
         treatment = factor(Treatment),
         corn_type = factor(`Corn Type`, labels=c("N", "G"), levels=c("Non - GM Corn", "GM CORN")),
         incidence_faw = as.numeric(incidence_faw))


cor_faw_wind_incidence <- cor(faw_ev$mean_wind, faw_ev$incidence_faw, method = "pearson", use = "pairwise.complete.obs")

cor_temp_incidence <- cor(faw_ev$mean_temp, faw_ev$incidence_faw, method = "pearson", use = "pairwise.complete.obs")

cor_faw_humid_incidence <- cor(faw_ev$mean_humid, faw_ev$incidence_faw, method = "pearson", use = "pairwise.complete.obs")

cor_faw_rain_incidence <- cor(faw_ev$mean_rain, faw_ev$incidence_faw, method = "pearson", use = "pairwise.complete.obs")


cor_faw_wind_incidence
cor_temp_incidence
cor_faw_humid_incidence
cor_faw_rain_incidence


# aphids
aphids_ev <-
  aphids_joined_ev %>%
  mutate(Province = factor(Province),
         Municipality = factor(Municipality),
         crop_stage = factor(`Crop Stage`),
         treatment = factor(Treatment),
         corn_type = factor(`Corn Type`, labels=c("N", "G"), levels=c("Non - GM Corn", "GM CORN")),
         incidence_aphids = as.numeric(incidence_aphids))


cor_aphids_wind_incidence <- cor(aphids_ev$mean_wind, aphids_ev$incidence_aphids, method = "pearson", use = "pairwise.complete.obs")

cor_temp_incidence <- cor(aphids_ev$mean_temp, aphids_ev$incidence_aphids, method = "pearson", use = "pairwise.complete.obs")

cor_aphids_humid_incidence <- cor(aphids_ev$mean_humid, aphids_ev$incidence_aphids, method = "pearson", use = "pairwise.complete.obs")

cor_aphids_rain_incidence <- cor(aphids_ev$mean_rain, aphids_ev$incidence_aphids, method = "pearson", use = "pairwise.complete.obs")


cor_aphids_wind_incidence
cor_temp_incidence
cor_aphids_humid_incidence
cor_aphids_rain_incidence


# borer
borer_ev <-
  borer_joined_ev %>%
  mutate(Province = factor(Province),
         Municipality = factor(Municipality),
         crop_stage = factor(`Crop Stage`),
         treatment = factor(Treatment),
         corn_type = factor(`Corn Type`, labels=c("N", "G"), levels=c("Non - GM Corn", "GM CORN")),
         incidence_borer = as.numeric(incidence_borer))


cor_borer_wind_incidence <- cor(borer_ev$mean_wind, borer_ev$incidence_borer, method = "pearson", use = "pairwise.complete.obs")

cor_temp_incidence <- cor(borer_ev$mean_temp, borer_ev$incidence_borer, method = "pearson", use = "pairwise.complete.obs")

cor_borer_humid_incidence <- cor(borer_ev$mean_humid, borer_ev$incidence_borer, method = "pearson", use = "pairwise.complete.obs")

cor_borer_rain_incidence <- cor(borer_ev$mean_rain, borer_ev$incidence_borer, method = "pearson", use = "pairwise.complete.obs")


cor_borer_wind_incidence
cor_temp_incidence
cor_borer_humid_incidence
cor_borer_rain_incidence


# earworm
earworm_ev <-
  earworm_joined_ev %>%
  mutate(Province = factor(Province),
         Municipality = factor(Municipality),
         crop_stage = factor(`Crop Stage`),
         treatment = factor(Treatment),
         corn_type = factor(`Corn Type`, labels=c("N", "G"), levels=c("Non - GM Corn", "GM CORN")),
         incidence_earworm = as.numeric(incidence_earworm))


cor_earworm_wind_incidence <- cor(earworm_ev$mean_wind, earworm_ev$incidence_earworm, method = "pearson", use = "pairwise.complete.obs")

cor_temp_incidence <- cor(earworm_ev$mean_temp, earworm_ev$incidence_earworm, method = "pearson", use = "pairwise.complete.obs")

cor_earworm_humid_incidence <- cor(earworm_ev$mean_humid, earworm_ev$incidence_earworm, method = "pearson", use = "pairwise.complete.obs")

cor_earworm_rain_incidence <- cor(earworm_ev$mean_rain, earworm_ev$incidence_earworm, method = "pearson", use = "pairwise.complete.obs")


cor_earworm_wind_incidence
cor_temp_incidence
cor_earworm_humid_incidence
cor_earworm_rain_incidence


# Armyworm
armyworm_ev <-
  armyworm_joined_ev %>%
  mutate(Province = factor(Province),
         Municipality = factor(Municipality),
         crop_stage = factor(`Crop Stage`),
         treatment = factor(Treatment),
         corn_type = factor(`Corn Type`, labels=c("N", "G"), levels=c("Non - GM Corn", "GM CORN")),
         incidence_armyworm = as.numeric(incidence_armyworm))


cor_armyworm_wind_incidence <- cor(armyworm_ev$mean_wind, armyworm_ev$incidence_armyworm, method = "pearson", use = "pairwise.complete.obs")

cor_temp_incidence <- cor(armyworm_ev$mean_temp, armyworm_ev$incidence_armyworm, method = "pearson", use = "pairwise.complete.obs")

cor_armyworm_humid_incidence <- cor(armyworm_ev$mean_humid, armyworm_ev$incidence_armyworm, method = "pearson", use = "pairwise.complete.obs")

cor_armyworm_rain_incidence <- cor(armyworm_ev$mean_rain, armyworm_ev$incidence_armyworm, method = "pearson", use = "pairwise.complete.obs")


cor_armyworm_wind_incidence
cor_temp_incidence
cor_armyworm_humid_incidence
cor_armyworm_rain_incidence


# Cutworm
cutworm_ev <-
  cutworm_joined_ev %>%
  mutate(Province = factor(Province),
         Municipality = factor(Municipality),
         crop_stage = factor(`Crop Stage`),
         treatment = factor(Treatment),
         corn_type = factor(`Corn Type`, labels=c("N", "G"), levels=c("Non - GM Corn", "GM CORN")),
         incidence_cutworm = as.numeric(incidence_cutworm))


cor_cutworm_wind_incidence <- cor(cutworm_ev$mean_wind, cutworm_ev$incidence_cutworm, method = "pearson", use = "pairwise.complete.obs")

cor_temp_incidence <- cor(cutworm_ev$mean_temp, cutworm_ev$incidence_cutworm, method = "pearson", use = "pairwise.complete.obs")

cor_cutworm_humid_incidence <- cor(cutworm_ev$mean_humid, cutworm_ev$incidence_cutworm, method = "pearson", use = "pairwise.complete.obs")

cor_cutworm_rain_incidence <- cor(cutworm_ev$mean_rain, cutworm_ev$incidence_cutworm, method = "pearson", use = "pairwise.complete.obs")


cor_cutworm_wind_incidence
cor_temp_incidence
cor_cutworm_humid_incidence
cor_cutworm_rain_incidence




hopper_ev <-
  hopper_joined_ev %>%
  mutate(Province = factor(Province),
         Municipality = factor(Municipality),
         crop_stage = factor(`Crop Stage`),
         treatment = factor(Treatment),
         corn_type = factor(`Corn Type`, labels=c("N", "G"), levels=c("Non - GM Corn", "GM CORN")),
         incidence_hopper = as.numeric(incidence_hopper))


cor_hopper_wind_incidence <- cor(hopper_ev$mean_wind, hopper_ev$incidence_hopper, method = "pearson", use = "pairwise.complete.obs")

cor_temp_incidence <- cor(hopper_ev$mean_temp, hopper_ev$incidence_hopper, method = "pearson", use = "pairwise.complete.obs")

cor_hopper_humid_incidence <- cor(hopper_ev$mean_humid, hopper_ev$incidence_hopper, method = "pearson", use = "pairwise.complete.obs")

cor_hopper_rain_incidence <- cor(hopper_ev$mean_rain, hopper_ev$incidence_hopper, method = "pearson", use = "pairwise.complete.obs")


cor_hopper_wind_incidence
cor_temp_incidence
cor_hopper_humid_incidence
cor_hopper_rain_incidence



detach("package:ltm", unload = TRUE)

```



```{r}
# library("bestNormalize")
# bestNorm_semilooper <- predict(bestNormalize(summary_semilooper$sum_incidence_semilooper, out_of_sample = FALSE, loo = TRUE))
# detach("package:bestNormalize", unload = TRUE)

# 
# # center_scale(x) tranformation according to bestNormalize
# summary_semilooper$orq <- bestNorm_semilooper
# 
# # Test of Normality after transformation
# ks_test_semilooper_trans <- ks.test(summary_semilooper$orq, 'pnorm')
# ad_test_semilooper_trans <- ad.test(summary_semilooper$orq)
# skew_semilooper_trans <- skewness(summary_semilooper$orq)
# kurt_semilooper_trans <- kurtosis(summary_semilooper$orq)
# jarq_semilooper_trans <- jarque.test(summary_semilooper$orq)
# 
# 
# # Test of Homoskedasticity after transformation
# levenes_fertilizer_semilooper_trans <- leveneTest(orq ~ Treatment, summary_semilooper)
# levenes_corntype_semilooper_trans <- leveneTest(orq ~ `Corn Type`, summary_semilooper)
# levenes_municipality_semilooper_trans <- leveneTest(orq ~ Municipality, summary_semilooper)
# levenes_province_semilooper_trans <- leveneTest(orq ~ Province, summary_semilooper)
# levenes_fert_corn_semilooper_trans <- leveneTest(orq ~ interaction(Treatment, `Corn Type`), summary_semilooper)
# 
# summary_semilooper %>%
#   ggplot(aes(orq)) +
#   geom_density()
# 
# # anova on Transformation
# aov_fert_semilooper_yj <- aov(orq ~ order_treat, summary_semilooper) %>% summary()
# aov_corn_semilooper_yj <- aov(orq ~ factor_corn, summary_semilooper) %>% summary()
# # Two way AnOVa
# 
# twoway_fert_corn_semilooper_yj <- aov(orq ~ order_treat + factor_corn, summary_semilooper) 
# tukey_fert_corn_semilooper <- TukeyHSD(twoway_fert_corn_semilooper_yj)
# 
# # AnOVa with Interaction
# aov_fert_corn_inter_semilooper_yj <- aov(orq ~ order_treat*factor_corn, summary_semilooper)  %>% summary()
```

















