---
title: "insects_forecast"
author: "Mihkail Cornell"
date: "2023-11-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
library(fpp2)
library(ggplot2)
library(dplyr)
library(stats)
library(ggpubr)
library(lubridate)
library(tidymodels)
library(scales)
library(forecast)
library(tsibble)
library(tidyverse)


library(patchwork) # To display 2 charts together
library(hrbrthemes)

insects_summary_overall <- read_csv("../insect_pests_and_diseases/pests_percent_incidences_dataset_with_weather.csv")

monthly_pest_percent_incidences_with_weather_data <-
  read_csv("../insect_pests_and_diseases/pests_forecast_dataset.csv")
```

```By Corn Type Top 3 Pests```
```{r}
plot_title_size <- 16
pests_labels <- c("Percent Incidence - Earworm" = "Earworm",
                  "Percent Incidence - Armyworm" = "Armyworm",
                  "Percent Incidence - Fall Armyworm" = "FAW"
                  )
pest_fills <- c(
            "Percent Incidence - Earworm" ="deepskyblue2",
            "Percent Incidence - Armyworm" = "chartreuse3",
            "Percent Incidence - Fall Armyworm" = "chocolate2"
            )


summary_pests_corntype_corntype_df <-
  monthly_pest_percent_incidences_with_weather_data %>%
  select(`Corn Type`, 
         `Percent Incidence - Fall Armyworm`, 
         `Percent Incidence - Earworm`, 
         `Percent Incidence - Armyworm`) %>%
  pivot_longer(-c(`Corn Type`), 
               names_to = "insects", 
               values_to = "incidences") %>%
  group_by(`Corn Type`, insects) %>%
  summarise(mean_pest_incidences = mean(incidences))




summary_pests_corntype_corntype_df %>%
  ggplot(aes(fct_reorder(insects,
                         mean_pest_incidences,
                         .desc = TRUE), 
             mean_pest_incidences,
             fill = insects)) +
  geom_col(show.legend = FALSE) +
  geom_text(aes(label = round(mean_pest_incidences, 2)),
                size = 5, color = "black", nudge_y = -3) +
  facet_grid(~ `Corn Type`, 
             scales = "free_x", 
             # space = "free_x",
             switch = "x") +
  scale_x_discrete(labels = pests_labels) +
  scale_fill_manual(values = pest_fills) +
  labs(title = "Pest Incidences on GM and Non-GM Corn Types",
       x = NULL,
       y = "Percent Incidences") +
  theme(
          plot.title.position = "panel",
          plot.title = element_text(margin = margin(b=12),
                                                    hjust = 0.5,
                                                    vjust = -98,
                                    size = plot_title_size + 2),
          plot.margin = margin(t = -10, l = 10, b = 30),
          aspect.ratio = 1,
          strip.background = element_blank(),
          strip.placement = "outside",
          axis.text = element_text(size = 12,
                                   color = "black",
                                   face = "plain",
                                   vjust = -0.5,
                                   margin = margin(b = 10)), 
          axis.title = element_text(size = 16),
          strip.text.x =  element_text(size = 12)
          )
ggsave("../Graphs_for_TERMINAL_Report/Summary of Pest Incidences on GM and Non-GM Corn.png", 
       dpi = 150, height = 5, width = 8)
```


``` Heatmap Corn Type - Crop Stage```
```{r}
pest_colors <- c(
            "`Percent Incidence - Earworm`" ="deepskyblue2",
            "`Percent Incidence - Armyworm`" = "chartreuse3",
            "`Percent Incidence - Fall Armyworm`" = "chocolate2"
            )

pests <- c("`Percent Incidence - Earworm`",
            "`Percent Incidence - Armyworm`",
            "`Percent Incidence - Fall Armyworm`"
            )

color_pests <- c("deepskyblue2", "chartreuse3", "chocolate2")

growth_stage <- c("Emergence", "Single Leaf", "Seedling (3 - 4 Leaves)",
                  "Early Whorl", "Mid Whorl", "Late Whorl",
                  "Tasseling", "Silking", "Maturity")

summary_pests_province_corntype_df <-
  insects_summary_overall %>%
  select(`Crop Stage`, `Corn Type`, 
         `Percent Incidence - Fall Armyworm`, 
         `Percent Incidence - Earworm`, 
         `Percent Incidence - Armyworm`) %>%
  pivot_longer(-c(`Crop Stage`, `Corn Type`), 
               names_to = "insects", 
               values_to = "incidences") %>%
  group_by(`Crop Stage`, `Corn Type`, insects) %>%
  summarise(mean_pest_incidences = mean(incidences)) %>%
  ungroup()



# faw
summary_pests_province_corntype_df %>%
  dplyr::filter(insects == "Percent Incidence - Fall Armyworm") %>%
  ggplot(aes(x = factor(`Crop Stage`, level = growth_stage), 
             y = factor(`Corn Type`, level = c("Non - GM Corn", "GM CORN")),
             fill = mean_pest_incidences,
             group = insects)) + 
  geom_tile() +
  scale_fill_gradient(low = "white", high = "chocolate2") +
  scale_x_discrete(guide = guide_axis(n.dodge = 2)) +
  geom_text(aes(label = round(mean_pest_incidences, 2)), 
            color = "black", size = 5) +
  labs(x = "Crop Stages",
       y = "Corn Types",
       fill = "FAW Mean \nPercent Incidence",
       title = "Heatmap of FAW Percent Incidence on Corn Types and Crop Stages") +
  theme(
        plot.margin = unit(c(0, 0, 2, 1), "cm"),
        plot.title.position = "panel",
        panel.background = element_blank(),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        plot.title = element_text(margin = margin(b = -20),
                                  hjust = 0.5,
                                  vjust = -75,
                                  size = 20),
        axis.title = element_text(size = 14,
                                  vjust = -1.8,
                                  margin = margin(t = 25, b = 15)),
        axis.text = element_text(color = "black",
                                 face = "plain",
                                 vjust = -0.75,
                                 size = 9,
                                 margin = margin(b = 8)),
        axis.ticks.length=unit(.25, "cm")
  )
ggsave("Corn Types and Crop Stage Heat map FAW.png", dpi = 150, width = 10)


# earworm
summary_pests_province_corntype_df %>%
  dplyr::filter(insects == "Percent Incidence - Earworm") %>%
  ggplot(aes(x = factor(`Crop Stage`, level = growth_stage), 
             y = factor(`Corn Type`, level = c("Non - GM Corn", "GM CORN")),
             fill = mean_pest_incidences,
             group = insects)) + 
  geom_tile() +
  scale_fill_gradient(low = "white", high = "deepskyblue2") +
  scale_x_discrete(guide = guide_axis(n.dodge = 2)) +
  geom_text(aes(label = round(mean_pest_incidences, 2)), 
            color = "black", size = 5) +
  labs(x = "Crop Stages",
       y = "Corn Types",
       fill = "Earworm Mean \nPercent Incidence",
       title = "Heatmap of Earworm Percent Incidence on Corn Types and Crop Stages") +
  theme(
        plot.margin = unit(c(0, 0, 2, 1), "cm"),
        plot.title.position = "panel",
        panel.background = element_blank(),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        plot.title = element_text(margin = margin(b = -20),
                                  hjust = 0.5,
                                  vjust = -75,
                                  size = 20),
        axis.title = element_text(size = 14,
                                  vjust = -1.8,
                                  margin = margin(t = 25, b = 15)),
        axis.text = element_text(color = "black",
                                 face = "plain",
                                 vjust = -0.75,
                                 size = 9,
                                 margin = margin(b = 8)),
        axis.ticks.length=unit(.25, "cm")
  )
ggsave("Corn Types and Crop Stage Heat map Earworm.png", dpi = 150, width = 10)


# armyworm
summary_pests_province_corntype_df %>%
  dplyr::filter(insects == "Percent Incidence - Armyworm") %>%
  ggplot(aes(x = factor(`Crop Stage`, level = growth_stage), 
             y = factor(`Corn Type`, level = c("Non - GM Corn", "GM CORN")),
             fill = mean_pest_incidences,
             group = insects)) + 
  geom_tile() +
  scale_fill_gradient(low = "white", high = "chartreuse3") +
  scale_x_discrete(guide = guide_axis(n.dodge = 2)) +
  geom_text(aes(label = round(mean_pest_incidences, 2)), 
            color = "black", size = 5) +
  labs(x = "Crop Stages",
       y = "Corn Types",
       fill = "Armyworm Mean \nPercent Incidence",
       title = "Heatmap of Armyworm Percent Incidence on Corn Types and Crop Stages") +
  theme(
        plot.margin = unit(c(0, 0, 2, 1), "cm"),
        plot.title.position = "panel",
        panel.background = element_blank(),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        plot.title = element_text(margin = margin(b = -20),
                                  hjust = 0.5,
                                  vjust = -75,
                                  size = 20),
        axis.title = element_text(size = 14,
                                  vjust = -1.8,
                                  margin = margin(t = 25, b = 15)),
        axis.text = element_text(color = "black",
                                 face = "plain",
                                 vjust = -0.75,
                                 size = 9,
                                 margin = margin(b = 8)),
        axis.ticks.length=unit(.25, "cm")
  )
ggsave("Corn Types and Crop Stage Heat map Armyworm.png", dpi = 150, width = 10)
```


```Plot for Monthly Humidity```
```{r}
monthly_pests_humidity_data <-
  read_csv("../insect_pests_and_diseases/pests_forecast_dataset.csv")
  
monthly_pests_humidity_df <-
  monthly_pests_humidity_data %>%
  left_join(monthly_averages, by = c("Year", "Month")) %>%
  ungroup() 

monthly_pests_humidity_pivot <-
  monthly_pests_humidity_df %>%
  dplyr::select(Year, Month, `Fall Armyworm`, Armyworm, Earworm, mean_humid) %>%
  pivot_longer(c("Earworm", 
                 "Armyworm", 
                 "Fall Armyworm"), 
               values_to = "incidence", 
               names_to = "insects") %>%
  mutate(time_period = paste(Year, Month, sep = "-"),
         time_period = ym(time_period)) %>%
  ungroup() %>%
  select(-Year, -Month)

month.breaks.vec <- c(as.Date("2020-06-01"),
               seq(from = as.Date("2020-06-01"), to = as.Date("2023-07-01"),
                 by = "month"),
               as.Date("2023-07-01"))

pest_colors <- c(
            "Earworm" ="deepskyblue2",
            "Armyworm" = "chartreuse3",
            "Fall Armyworm" = "chocolate2"
            )


linewidth = 2.2
title_text_size = 15
axis_text_size = 11

monthly_pests_humidity_pivot %>% 
  ggplot(aes(x = time_period, 
             y = incidence,
             order = incidence)) +
    scale_y_continuous(
               breaks = seq(0, 80, 2.5),
               sec.axis = sec_axis(~. , name = "Monthly Humidity")) +
    geom_line(aes(time_period, 
                  incidence, 
                  color = insects),
              linewidth = linewidth + 0.5,
              position = position_dodge(1)) +
    scale_x_date(date_labels = format("%b-%Y"),
                 date_breaks = "1 month",
                 breaks = month.breaks.vec)  +
    geom_line(aes(y = mean_humid,
                  alpha = 0.9),
                  linewidth = linewidth,
                  show.legend = FALSE) +
    geom_area(aes(fill = mean_humid),
              alpha = 0.3,
              position = "identity",
              fill = "gray") +
    labs(y = "Percent Incidence",
         x = "Cropping Months",
         title = "Mean Monthly Pest Incidences and Mean Humidity from May 2020 - Aug 2023",
         color = "Arthropod Pests",
         caption = "*Monthly average humidity is in GRAY") +
    scale_color_manual(values = color_pests) +
    theme(
          plot.title.position = "panel",
          plot.title = element_text(margin = margin(t=14),
                                    hjust = 0.5,
                                    vjust = -115,
                                    size = plot_title_size + 6),
          plot.margin = margin(1,1,1.5,1.2, "cm"),
          plot.caption = element_text(hjust = 0.8),
          panel.background = element_rect(fill = NA),
          panel.grid.major = element_line(colour = "gray95"), 
          axis.text.x = element_text(margin = margin(b = 10),
                                     angle = 90, 
                                     vjust = 0.5, 
                                     size = axis_text_size + 3),
          axis.ticks = element_blank(),
          axis.text.y = element_text(margin = margin(b = 8, l = 4),
                                     vjust = 1, 
                                     hjust = 1, 
                                     size = axis_text_size),
          axis.title = element_text(size = title_text_size, face="bold",
                                    margin = margin(t = 13)),
          axis.ticks.y = element_blank(),
          legend.title = element_blank(),
          legend.position = c(0.6, 0.6), 
          legend.justification = c(0.2, 1.1), 
          legend.background = element_rect(fill = NA, colour = NA)
          )
ggsave("Summary of Monthly Pest Incidences and Mean Humidity from May 2020 - Aug 2023.png", 
       dpi = 150, height = 8, width = 12)


```


```Plot for Monthly Temperature```
```{r setup, include=FALSE, fig.width = 12, fig.height = 7}
monthly_pests_temperature_data <-
  read_csv("../insect_pests_and_diseases/pests_forecast_dataset.csv")
  
monthly_pests_temperature_df <-
  monthly_pests_temperature_data %>%
  left_join(monthly_averages, by = c("Year", "Month")) %>%
  ungroup() 

monthly_pests_temperature_pivot <-
  monthly_pests_temperature_df %>%
  dplyr::select(Year, Month, `Fall Armyworm`, Armyworm, Earworm, mean_temp) %>%
  pivot_longer(c("Earworm", 
                 "Armyworm", 
                 "Fall Armyworm"), 
               values_to = "incidence", 
               names_to = "insects") %>%
  mutate(time_period = paste(Year, Month, sep = "-"),
         time_period = ym(time_period)) %>%
  ungroup() %>%
  select(-Year, -Month)


monthly_pests_temperature_pivot  %>%
    ggplot(aes(x = time_period, 
               y = incidence,
               order = incidence)) +
    scale_y_continuous(limits = c(0, 32),
               breaks = seq(0, 32, 0.75),
               sec.axis = sec_axis(~. , name = "Monthly Temperature")) +
    geom_line(aes(time_period, 
                  incidence, 
                  color = insects),
                  linewidth = linewidth + 0.2,
                  position = position_dodge(1)) +
    scale_x_date(date_labels = format("%b-%Y"),
                 date_breaks = "1 month") +
    geom_line(aes(y = mean_temp,
                  alpha = 0.9),
                  linewidth = linewidth,
                  show.legend = FALSE) +
    geom_area(alpha = 0.3,
              show.legend = FALSE,
              position = "identity",
              fill = "gray") +
    labs(y = "Percent Incidence",
         x = "Cropping Months",
         title = "Mean Monthly Pest Incidences and Mean Temperature from May 2020 - Aug 2023",
         caption = "*Monthly average temperature is in GRAY") +
    scale_color_manual(values = color_pests) +
    theme(
          plot.title.position = "panel",
          plot.title = element_text(margin = margin(t=12),
                                                    hjust = 0.5,
                                                    vjust = -120,
                                    size = plot_title_size + 6),
          plot.margin = margin(0,1,1.5,1.2, "cm"),
          plot.caption = element_text(hjust = 0.8),
          panel.background = element_rect(fill = NA),
          panel.grid.major = element_line(colour = "gray95"), 
          axis.text.x = element_text(margin = margin(b = 10),
                                     angle = 90, 
                                     vjust = 2, 
                                     hjust = 1, 
                                     size = axis_text_size + 3),
          axis.text.y = element_text(margin = margin(b = 5, l = 2),
                                     vjust = 1, 
                                     hjust = 1, 
                                     size = axis_text_size - 1),
          axis.title = element_text(size = title_text_size + 2, face="bold",
                                    margin = margin(t = 10)),
          axis.ticks.y = element_blank(),
          legend.title = element_blank(),
          legend.position = c(0.75, 0.8), 
          legend.justification = c(0.2, 1.1), 
          legend.background = element_rect(fill = NA, colour = NA)
          )
ggsave("Summary of Monthly Pest Incidences and Mean Temperature from May 2020 - Aug 2023.png", 
       dpi = 150, height = 8, width = 12)


```


```Plot for Monthly Rainfall```
```{r setup, include=FALSE, fig.width = 12, fig.height = 7}

monthly_pests_rainfall_pivot <-
  monthly_pests_temperature_df %>%
  dplyr::select(Year, Month, `Fall Armyworm`, Armyworm, Earworm, mean_rain) %>%
  pivot_longer(c("Earworm", 
                 "Armyworm", 
                 "Fall Armyworm"), 
               values_to = "incidence", 
               names_to = "insects") %>%
  mutate(time_period = paste(Year, Month, sep = "-"),
         time_period = ym(time_period)) %>%
  ungroup() %>%
  select(-Year, -Month)


monthly_pests_rainfall_pivot  %>%
    ggplot(aes(x = time_period, 
               y = incidence,
               order = incidence)) +
    scale_y_continuous(limits = c(0, 32),
               breaks = seq(0, 30, 0.75),
               sec.axis = sec_axis(~. , name = "Monthly Rainfall")) +
    geom_line(aes(time_period, 
                  incidence, 
                  color = insects),
                  linewidth = linewidth + 0.2,
                  position = position_dodge(1)) +
    scale_x_date(date_labels = format("%b-%Y"),
                 date_breaks = "1 month") +
    geom_line(aes(y = mean_rain,
                  alpha = 0.9),
                  linewidth = linewidth,
                  show.legend = FALSE) +
    geom_area(alpha = 0.3,
              show.legend = FALSE,
              position = "identity",
              fill = "gray") +
    labs(y = "Percent Incidence",
         x = "Cropping Months",
         title = "Mean Monthly Pest Incidences and Mean Rainfall from May 2020 - Aug 2023",
         caption = "*Monthly average rainfall is in GRAY") +
    scale_color_manual(values = color_pests) +
    theme(
          plot.title.position = "panel",
          plot.title = element_text(margin = margin(t=12),
                                                    hjust = 0.5,
                                                    vjust = -120,
                                    size = plot_title_size + 6),
          plot.margin = margin(0,1,1.5,1.2, "cm"),
          plot.caption = element_text(hjust = 0.8),
          panel.background = element_rect(fill = NA),
          panel.grid.major = element_line(colour = "gray95"), 
          axis.text.x = element_text(margin = margin(b = 10),
                                     angle = 90, 
                                     vjust = 2, 
                                     hjust = 1, 
                                     size = axis_text_size + 3),
          axis.text.y = element_text(margin = unit(c(0, 0.5, 0, 0), "cm"),
                                     vjust = 1, 
                                     hjust = 1, 
                                     size = axis_text_size - 2),
          axis.title = element_text(size = title_text_size + 2, face="bold",
                                    margin = margin(t = 10)),
          axis.ticks.y = element_blank(),
          legend.title = element_blank(),
          legend.position = c(0.75, 0.8), 
          legend.justification = c(0.2, 1.1), 
          legend.background = element_rect(fill = NA, colour = NA)
          )
ggsave("Summary of Monthly Pest Incidences and Mean Rainfall from May 2020 - Aug 2023.png", 
       dpi = 150, height = 8, width = 12)


```


```Plot for Monthly Wind Speed```
```{r setup, include=FALSE, fig.width = 12, fig.height = 7}

monthly_pests_wind_pivot <-
  monthly_pests_temperature_df %>%
  dplyr::select(Year, Month, `Fall Armyworm`, Armyworm, Earworm, mean_wind) %>%
  pivot_longer(c("Earworm", 
                 "Armyworm", 
                 "Fall Armyworm"), 
               values_to = "incidence", 
               names_to = "insects") %>%
  mutate(time_period = paste(Year, Month, sep = "-"),
         time_period = ym(time_period)) %>%
  ungroup() %>%
  select(-Year, -Month)


monthly_pests_wind_pivot  %>%
    ggplot(aes(x = time_period, 
               y = incidence,
               order = incidence)) +
    scale_y_continuous(limits = c(0, 32),
               breaks = seq(0, 30, 0.75),
               sec.axis = sec_axis(~. , name = "Monthly Wind Speed")) +
    geom_line(aes(time_period, 
                  incidence, 
                  color = insects),
                  linewidth = linewidth + 0.2,
                  position = position_dodge(1)) +
    scale_x_date(date_labels = format("%b-%Y"),
                 date_breaks = "1 month") +
    geom_line(aes(y = mean_wind,
                  alpha = 0.9),
                  linewidth = linewidth,
                  show.legend = FALSE) +
    geom_area(alpha = 0.3,
              show.legend = FALSE,
              position = "identity",
              fill = "gray") +
    labs(y = "Percent Incidence",
         x = "Cropping Months",
         title = "Mean Monthly Pest Incidences and Mean Wind Speed from May 2020 - Aug 2023",
         caption = "*Monthly average wind speed is in GRAY") +
    scale_color_manual(values = color_pests) +
    theme(
          plot.title.position = "panel",
          plot.title = element_text(margin = margin(t=12),
                                                    hjust = 0.5,
                                                    vjust = -122,
                                    size = plot_title_size + 6),
          plot.margin = margin(0,1,1.5,1.2, "cm"),
          plot.caption = element_text(hjust = 0.9),
          panel.background = element_rect(fill = NA),
          panel.grid.major = element_line(colour = "gray95"), 
          axis.text.x = element_text(margin = margin(b = 10),
                                     angle = 90, 
                                     vjust = 2, 
                                     hjust = 1, 
                                     size = axis_text_size + 3),
          axis.text.y = element_text(margin = unit(c(0, 0.5, 0, 0), "cm"),
                                     vjust = 1, 
                                     hjust = 1, 
                                     size = axis_text_size - 2),
          axis.title = element_text(size = title_text_size + 2, face="bold",
                                    margin = margin(t = 10)),
          axis.ticks.y = element_blank(),
          legend.title = element_blank(),
          legend.position = c(0.75, 0.8), 
          legend.justification = c(0.2, 1.1), 
          legend.background = element_rect(fill = NA, colour = NA)
          )
ggsave("Summary of Monthly Pest Incidences and Mean Wind Speed from May 2020 - Aug 2023.png", 
       dpi = 150, height = 8, width = 12)


```

```By cropping season```
```{r}
crop_growth_stages_monthly <- c("Emergence", "Single Leaf", 
                                "Seedling (3 - 4 Leaves)", 
                                "Early Whorl", "Mid Whorl", 
                                "Late Whorl", "Tasseling", 
                                "Silking", "Maturity")

# first cropping 2020
insects_1stcrop_2020 <-
  insects_ts_df %>%
  filter(year(ymd(month)) == "2020") %>% 
  group_by(month, `Crop Stage`) %>%
  arrange(month, match(`Crop Stage`, crop_growth_stages_monthly))

# 2nd cropping 2021
insects_2ndcrop_2021_july <-
  insects_ts_df %>%
    filter(year(ymd(month)) == "2021",
           month(ymd(month)) == 7, 
           `Crop Stage` %in% c("Late Whorl", "Tasseling", 
                                "Silking", "Maturity"))

insects_2ndcrop_2021 <-
  insects_ts_df %>%
    filter(year(ymd(month)) == "2021", month(ymd(month)) %in% seq(1, 7)) %>% 
    group_by(month, `Crop Stage`) %>%
    ungroup() %>% 
    arrange(month, match(`Crop Stage`, crop_growth_stages_monthly)) %>%
  full_join(insects_2ndcrop_2021_july)



# 3rd cropping 2021 - 2022
insects_3rdcrop_2021_july <-
  insects_ts_df %>%
    filter(year(ymd(month)) == "2021",
           month(ymd(month)) == 7, 
           `Crop Stage` %in% c("Single Leaf", 
                                "Seedling (3 - 4 Leaves)", 
                                "Early Whorl", "Mid Whorl"))
insects_3rdcrop_2022_january <-
  insects_ts_df %>%
    filter(year(ymd(month)) == "2022" & month(ymd(month)) == 1)

insects_3rdcrop_2021 <-
  insects_ts_df %>%
    filter(year(ymd(month)) == "2021" & month(ymd(month)) %in% seq(7, 9)) %>% 
    group_by(month, `Crop Stage`) %>%
    arrange(month, match(`Crop Stage`, crop_growth_stages_monthly)) %>%
    full_join(insects_3rdcrop_2021_july) %>%
    full_join(insects_3rdcrop_2022_january)



# 4th cropping 2022
insects_4thcrop_2022_may <-
  insects_ts_df %>%
    filter(year(ymd(month)) == "2022",
           month(ymd(month)) == 5, 
           `Crop Stage` %in% c("Late Whorl", "Tasseling", 
                                "Silking", "Maturity"))

insects_4thcrop_2022 <-
  insects_ts_df %>%
    filter(year(ymd(month)) == "2022", month(ymd(month)) %in% seq(2, 4)) %>% 
    group_by(month, `Crop Stage`) %>%
    arrange(month, match(`Crop Stage`, crop_growth_stages_monthly)) %>%
  full_join(insects_4thcrop_2022_may)



# 5th cropping 2022
insects_5thcrop_2022_may <-
  insects_ts_df %>%
    filter(year(ymd(month)) == "2022",
           month(ymd(month)) %in% c(4, 5),
           `Crop Stage` %in% c("Single Leaf", 
                                "Seedling (3 - 4 Leaves)", 
                                "Early Whorl", "Mid Whorl"))

insects_5thcrop_january <-
  insects_ts_df %>%
     filter(year(ymd(month)) == "2023",
            month(ymd(month)) %in% c(1, 2, 3), 
           `Crop Stage` %in% c("Late Whorl", "Tasseling", 
                                "Silking", "Maturity"))

insects_5thcrop_2022 <-
  insects_5thcrop_2022_may %>% 
  full_join(
    insects_ts_df %>%
        filter(
        year(ymd(month)) == "2022", 
        month(ymd(month)) %in% seq(6, 12)) %>% 
        group_by(month, `Crop Stage`) %>%
        arrange(month, match(`Crop Stage`, crop_growth_stages_monthly))) %>%
  full_join(insects_5thcrop_january)







# 6th cropping 2023
insects_6thcrop_february <-
  insects_ts_df %>%
    filter(year(ymd(month)) == "2023",
           month(ymd(month)) %in% c(2, 3), 
           `Crop Stage` %in% c("Single Leaf", 
                                "Seedling (3 - 4 Leaves)", 
                                "Early Whorl", "Mid Whorl"))


insects_6thcrop <-
  insects_ts_df %>%
    filter(year(ymd(month)) == "2023", 
           month(ymd(month)) %in% seq(4, 12)) %>% 
    group_by(month, `Crop Stage`) %>%
    arrange(month, match(`Crop Stage`, crop_growth_stages_monthly)) %>%
    full_join(insects_6thcrop_february)
```

```{r setup, include=FALSE, fig.width = 12, fig.height = 7}

# data
monthly_pests


monthly_pest_df <- 
  monthly_pests %>%
  mutate(time_period = paste(Year, Month, sep = "-")) %>%
  select(-Year, -Month) %>%
  pivot_longer(starts_with("incidence_"), names_to = "insects", values_to = "incidence")


monthly_temp_plot <-
  monthly_pest_df %>%
  ggplot(aes(x = time_period, 
             y = insects, 
             group = insects)) +
  geom_area(aes(y = temperature), 
            stat = "identity", 
            alpha = 0.2,
            show.legend = FALSE) 


ggplot() +
  geom_line(data = insects_average_df_monthly_aes,
             aes(month, monthly_incidence, color = pest_incidence),
             linewidth = line_size) +
  scale_x_date(date_labels = format("%b-%Y"),
               date_breaks = "1 month") +
  scale_color_manual(values = pest_colors, labels = pests) +
  geom_line(linewidth = linewidth - 0.2,
            position = position_dodge(1)) +
  # scale_x_discrete(limits = month,
  #                  labels = month) +
  scale_y_continuous(limits = c(0, 35), 
                     breaks = c(seq(0, 20, by = 5)),
                     sec.axis = sec_axis(~., 
                                         name = "Monthly Temperature")) +
  labs(y = "Percent Incidence",
       x = "Cropping Months",
       title = "Summary of Monthly Pest Incidences from May 2020 - Aug 2023") +
  theme(axis.text.x = element_text(angle = 35, 
                                   vjust = 1, 
                                   hjust = 1, 
                                   size = 8),
        axis.title = element_text(size = 11, face="bold")) +
  scale_color_brewer(palette = "Paired") +
  theme(plot.title.position = "panel",
        plot.title = element_text(margin = margin(t=5, b=15),
                                  hjust = 0.5,
                                  vjust = -133),
        plot.margin = margin(t = -10, l = 10, b = 20))
ggsave("Summary of Monthly Pest Incidences from May 2020 - Aug 2023.png", dpi = plot_dpi, height = plot_height)
```

